## Install Required Libraries

ในการเชื่อมต่อฐานข้อมูล PostgreSQL และจัดการข้อมูลด้วย Python  
จำเป็นต้องติดตั้งไลบรารีดังต่อไปนี้:

- **psycopg2-binary** → สำหรับเชื่อมต่อ PostgreSQL  
- **pandas** → สำหรับจัดการข้อมูล (Data Analysis)  
- **sqlalchemy** → สำหรับจัดการ database connection แบบขั้นสูง

In [117]:
!pip install psycopg2-binary pandas sqlalchemy

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [118]:
import psycopg2
import pandas as pd

## เชื่อมต่อ Postgres

In [119]:
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="postgres",   # database เริ่มต้น
    user="postgres",
    password="admin"
)

conn.autocommit = True
cur = conn.cursor()

## สร้าง Database

In [120]:
cur.execute("CREATE DATABASE thai_stock_market;")

DuplicateDatabase: database "thai_stock_market" already exists

In [ ]:
cur.close()
conn.close()

In [6]:
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="thai_stock_market",
    user="postgres",
    password="admin"
)

conn.autocommit = True
cur = conn.cursor()
print("Connected to thai_stock_market")

Connected to thai_stock_market

## table categories

In [7]:
cur.execute("""
CREATE TABLE IF NOT EXISTS categories (
    category_id SERIAL PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL
);
""")

## table stocks

In [8]:
cur.execute("""
CREATE TABLE IF NOT EXISTS stocks (
    stock_id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    stock_name TEXT,
    category_id INT REFERENCES categories(category_id),
    pe NUMERIC(10, 2),
    pbv NUMERIC(10, 2),
    eps NUMERIC(10, 2),
    div_yield NUMERIC(10, 2)   
);
""")

## table prices

In [9]:
cur.execute("""
CREATE TABLE IF NOT EXISTS prices (
    price_id SERIAL PRIMARY KEY,
    stock_id INT REFERENCES stocks(stock_id),
    trade_date DATE,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume BIGINT,
    market_cap NUMERIC
);
""")

In [10]:
import pandas as pd

pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
""", conn)

/var/folders/31/9k1nqy5s707g8pz9zy6gwnyr0000gn/T/ipykernel_95819/1863747298.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("""

   table_name
0  categories
1      stocks
2      prices

### SETTRADE API

In [11]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.3)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (44.0.1)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.12.2)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=37.0->settrade-v2) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2025.8.3)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [12]:
#import และตั้งค่า Credential
from settrade_v2 import Investor
from pprint import pprint

In [13]:
from settrade_v2 import Investor

APP_ID = "BDYsxwFdwr4CGrqn"
APP_SECRET = "c/YrEWTsD6i7kfib8tF022qBrvNoNKh0jnUsqBtCurQ="
BROKER_ID = "SANDBOX"
APP_CODE = "SANDBOX"

investor = Investor(
    app_id=APP_ID,
    app_secret=APP_SECRET,
    broker_id=BROKER_ID,
    app_code=APP_CODE,
    is_auto_queue=False
)

print("API Connected")

API Connected

In [14]:
market = investor.MarketData()

### เลือกรายชื่อหุ้นเอง (เพราะ API ไม่มี get_security_list)
### ดึงข้อมูลย้อนหลัง 1 ปี 
หลักการ
ใช้ timeframe รายวัน (1d)
1 ปี ≈ 250–260 วันทำการ
API ใช้ limit ไม่ได้ใช้ start_date

In [16]:
import pandas as pd
from sqlalchemy import create_engine, text

In [19]:
import pandas as pd

symbols_df = pd.DataFrame({
    "symbol": [
        
    ]
})

# แปลงเป็น list
symbols = symbols_df["symbol"].tolist()

In [21]:
symbols

['2S',
 '3BBIF',
 '88TH',
 'A',
 'A5',
 'AAI',
 'AAV',
 'ABM',
 'ACAP',
 'ACC',
 'ACE',
 'ACG',
 'ADB',
 'ADD',
 'ADVANC',
 'ADVICE',
 'AE',
 'AEONTS',
 'AF',
 'AFC',
 'AGE',
 'AH',
 'AHC',
 'AI',
 'AIE',
 'AIMCG',
 'AIMIRT',
 'AIRA',
 'AIT',
 'AJ',
 'AJA',
 'AKP',
 'AKR',
 'AKS',
 'ALLA',
 'ALLY',
 'ALPHAX',
 'ALT',
 'ALUCON',
 'AMA',
 'AMANAH',
 'AMARC',
 'AMARIN',
 'AMATA',
 'AMATAR',
 'AMATAV',
 'AMC',
 'AMR',
 'ANAN',
 'ANI',
 'AOT',
 'AP',
 'APCO',
 'APCS',
 'APO',
 'APP',
 'APURE',
 'AQUA',
 'ARIN',
 'ARIP',
 'ARROW',
 'AS',
 'ASAP',
 'ASEFA',
 'ASIA',
 'ASIAN',
 'ASIMAR',
 'ASK',
 'ASN',
 'ASP',
 'ASW',
 'ATLAS',
 'ATP30',
 'AU',
 'AUCT',
 'AURA',
 'AWC',
 'AXTRART',
 'AYUD',
 'B',
 'B52',
 'BA',
 'BAFS',
 'BAM',
 'BANPU',
 'BAREIT',
 'BAY',
 'BBGI',
 'BBIK',
 'BBL',
 'BC',
 'BCH',
 'BCP',
 'BCPG',
 'BCT',
 'BDMS',
 'BE8',
 'BEAUTY',
 'BEC',
 'BEM',
 'BEYOND',
 'BGC',
 'BGRIM',
 'BGT',
 'BH',
 'BIG',
 'BIOTEC',
 'BIS',
 'BIZ',
 'BJC',
 'BJCHI',
 'BKA',
 'BKD',
 'BKGI',
 'BKIH',
 'BLA',
 'BLAND',
 'BLC',
 'BLESS',
 'BLISS',
 'BM',
 'BOFFICE',
 'BOL',
 'BPP',
 'BPS',
 'BR',
 'BRI',
 'BROCK',
 'BRR',
 'BRRGIF',
 'BSBM',
 'BSM',
 'BTC',
 'BTG',
 'BTNC',
 'BTS',
 'BTSGIF',
 'BTW',
 'BUI',
 'BVG',
 'BWG',
 'B-WORK',
 'BYD',
 'CAZ',
 'CBG',
 'CCET',
 'CCP',
 'CEN',
 'CENTEL',
 'CEYE',
 'CFARM',
 'CFRESH',
 'CGD',
 'CGH',
 'CH',
 'CHAO',
 'CHARAN',
 'CHASE',
 'CHAYO',
 'CHEWA',
 'CHG',
 'CHIC',
 'CHO',
 'CHOTI',
 'CHOW',
 'CI',
 'CIG',
 'CIMBT',
 'CITY',
 'CIVIL',
 'CK',
 'CKP',
 'CM',
 'CMAN',
 'CMC',
 'CMO',
 'CMR',
 'CNT',
 'COCOCO',
 'COLOR',
 'COM7',
 'COMAN',
 'CPALL',
 'CPANEL',
 'CPAXT',
 'CPF',
 'CPH',
 'CPI',
 'CPL',
 'CPN',
 'CPNCG',
 'CPNREIT',
 'CPR',
 'CPT',
 'CPTREIT',
 'CPW',
 'CRANE',
 'CRC']

In [39]:
symbols = ["2S","3BBIF","88TH","A","A5","AAI","AAV","ABM","ACAP","ACC","ACE","ACG","ADB","ADD",
        "ADVANC","ADVICE","AE","AEONTS","AF","AFC","AGE","AH","AHC","AI","AIE","AIMCG","AIMIRT",
        "AIRA","AIT","AJ","AJA","AKP","AKR","AKS","ALLA","ALLY","ALPHAX","ALT","ALUCON","AMA",
        "AMANAH","AMARC","AMARIN","AMATA","AMATAR","AMATAV","AMC","AMR","ANAN","ANI","AOT","AP",
        "APCO","APCS","APO","APP","APURE","AQUA","ARIN","ARIP","ARROW","AS","ASAP","ASEFA","ASIA",
        "ASIAN","ASIMAR","ASK","ASN","ASP","ASW","ATLAS","ATP30","AU","AUCT","AURA","AWC","AXTRART",
        "AYUD","B","B52","BA","BAFS","BAM","BANPU","BAREIT","BAY","BBGI","BBIK","BBL","BC","BCH",
        "BCP","BCPG","BCT","BDMS","BE8","BEAUTY","BEC","BEM","BEYOND","BGC","BGRIM","BGT","BH",
        "BIG","BIOTEC","BIS","BIZ","BJC","BJCHI","BKA","BKD","BKGI","BKIH","BLA","BLAND","BLC",
        "BLESS","BLISS","BM","BOFFICE","BOL","BPP","BPS","BR","BRI","BROCK","BRR","BRRGIF","BSBM",
        "BSM","BTC","BTG","BTNC","BTS","BTSGIF","BTW","BUI","BVG","BWG","B-WORK","BYD","CAZ",
        "CBG","CCET","CCP","CEN","CENTEL","CEYE","CFARM","CFRESH","CGD","CGH","CH","CHAO",
        "CHARAN","CHASE","CHAYO","CHEWA","CHG","CHIC","CHO","CHOTI","CHOW","CI","CIG","CIMBT",
        "CITY","CIVIL","CK","CKP","CM","CMAN","CMC","CMO","CMR","CNT","COCOCO","COLOR","COM7",
        "COMAN","CPALL","CPANEL","CPAXT","CPF","CPH","CPI","CPL","CPN","CPNCG","CPNREIT","CPR",
        "CPT","CPTREIT","CPW","CRANE","CRC"]

all_data = []

for symbol in symbols:
    print(f"กำลังดึง {symbol}")
    data = market.get_candlestick(
        symbol=symbol,
        interval="1d",
        limit=260
    )
    df = pd.DataFrame(data)
    df["symbol"] = symbol
    all_data.append(df)

final_df = pd.concat(all_data)
final_df

กำลังดึง 2S
กำลังดึง 3BBIF
กำลังดึง 88TH
กำลังดึง A
กำลังดึง A5
กำลังดึง AAI
กำลังดึง AAV
กำลังดึง ABM
กำลังดึง ACAP
กำลังดึง ACC
กำลังดึง ACE
กำลังดึง ACG
กำลังดึง ADB
กำลังดึง ADD
กำลังดึง ADVANC
กำลังดึง ADVICE
กำลังดึง AE
กำลังดึง AEONTS
กำลังดึง AF
กำลังดึง AFC
กำลังดึง AGE
กำลังดึง AH
กำลังดึง AHC
กำลังดึง AI
กำลังดึง AIE
กำลังดึง AIMCG
กำลังดึง AIMIRT
กำลังดึง AIRA
กำลังดึง AIT
กำลังดึง AJ
กำลังดึง AJA
กำลังดึง AKP
กำลังดึง AKR
กำลังดึง AKS
กำลังดึง ALLA
กำลังดึง ALLY
กำลังดึง ALPHAX
กำลังดึง ALT
กำลังดึง ALUCON
กำลังดึง AMA
กำลังดึง AMANAH
กำลังดึง AMARC
กำลังดึง AMARIN
กำลังดึง AMATA
กำลังดึง AMATAR
กำลังดึง AMATAV
กำลังดึง AMC
กำลังดึง AMR
กำลังดึง ANAN
กำลังดึง ANI
กำลังดึง AOT
กำลังดึง AP
กำลังดึง APCO
กำลังดึง APCS
กำลังดึง APO
กำลังดึง APP
กำลังดึง APURE
กำลังดึง AQUA
กำลังดึง ARIN
กำลังดึง ARIP
กำลังดึง ARROW
กำลังดึง AS
กำลังดึง ASAP
กำลังดึง ASEFA
กำลังดึง ASIA
กำลังดึง ASIAN
กำลังดึง ASIMAR
กำลังดึง ASK
กำลังดึง ASN
กำลังดึง ASP
กำลังดึง ASW
กำลังดึง ATLAS
กำลังดึง ATP30
กำลังดึง AU
กำลังดึง AUCT
กำลังดึง AURA
กำลังดึง AWC
กำลังดึง AXTRART
กำลังดึง AYUD
กำลังดึง B
กำลังดึง B52
กำลังดึง BA
กำลังดึง BAFS
กำลังดึง BAM
กำลังดึง BANPU
กำลังดึง BAREIT
กำลังดึง BAY
กำลังดึง BBGI
กำลังดึง BBIK
กำลังดึง BBL
กำลังดึง BC
กำลังดึง BCH
กำลังดึง BCP
กำลังดึง BCPG
กำลังดึง BCT
กำลังดึง BDMS
กำลังดึง BE8
กำลังดึง BEAUTY
กำลังดึง BEC
กำลังดึง BEM
กำลังดึง BEYOND
กำลังดึง BGC
กำลังดึง BGRIM
กำลังดึง BGT
กำลังดึง BH
กำลังดึง BIG
กำลังดึง BIOTEC
กำลังดึง BIS
กำลังดึง BIZ
กำลังดึง BJC
กำลังดึง BJCHI
กำลังดึง BKA
กำลังดึง BKD
กำลังดึง BKGI
กำลังดึง BKIH
กำลังดึง BLA
กำลังดึง BLAND
กำลังดึง BLC
กำลังดึง BLESS
กำลังดึง BLISS
กำลังดึง BM
กำลังดึง BOFFICE
กำลังดึง BOL
กำลังดึง BPP
กำลังดึง BPS
กำลังดึง BR
กำลังดึง BRI
กำลังดึง BROCK
กำลังดึง BRR
กำลังดึง BRRGIF
กำลังดึง BSBM
กำลังดึง BSM
กำลังดึง BTC
กำลังดึง BTG
กำลังดึง BTNC
กำลังดึง BTS
กำลังดึง BTSGIF
กำลังดึง BTW
กำลังดึง BUI
กำลังดึง BVG
กำลังดึง BWG
กำลังดึง B-WORK
กำลังดึง BYD
กำลังดึง CAZ
กำลังดึง CBG
กำลังดึง CCET
กำลังดึง CCP
กำลังดึง CEN
กำลังดึง CENTEL
กำลังดึง CEYE
กำลังดึง CFARM
กำลังดึง CFRESH
กำลังดึง CGD
กำลังดึง CGH
กำลังดึง CH
กำลังดึง CHAO
กำลังดึง CHARAN
กำลังดึง CHASE
กำลังดึง CHAYO
กำลังดึง CHEWA
กำลังดึง CHG
กำลังดึง CHIC
กำลังดึง CHO
กำลังดึง CHOTI
กำลังดึง CHOW
กำลังดึง CI
กำลังดึง CIG
กำลังดึง CIMBT
กำลังดึง CITY
กำลังดึง CIVIL
กำลังดึง CK
กำลังดึง CKP
กำลังดึง CM
กำลังดึง CMAN
กำลังดึง CMC
กำลังดึง CMO
กำลังดึง CMR
กำลังดึง CNT
กำลังดึง COCOCO
กำลังดึง COLOR
กำลังดึง COM7
กำลังดึง COMAN
กำลังดึง CPALL
กำลังดึง CPANEL
กำลังดึง CPAXT
กำลังดึง CPF
กำลังดึง CPH
กำลังดึง CPI
กำลังดึง CPL
กำลังดึง CPN
กำลังดึง CPNCG
กำลังดึง CPNREIT
กำลังดึง CPR
กำลังดึง CPT
กำลังดึง CPTREIT
กำลังดึง CPW
กำลังดึง CRANE
กำลังดึง CRC

,lastSequence,time,open,high,low,close,volume,value,symbol
0,2306562,1.741194e+09,2.26,2.26,2.20,2.26,48974.0,0.0,2S
1,2306562,1.741280e+09,2.14,2.20,2.10,2.18,82189.0,0.0,2S
2,2306562,1.741540e+09,2.12,2.16,2.12,2.16,329118.0,0.0,2S
3,2306562,1.741626e+09,2.18,2.22,2.14,2.20,126722.0,0.0,2S
4,2306562,1.741712e+09,2.18,2.22,2.16,2.20,35230.0,0.0,2S
...,...,...,...,...,...,...,...,...,...
255,2127731,1.774458e+09,18.10,18.30,17.90,18.30,22095470.0,0.0,CRC
256,2127731,1.774544e+09,18.40,18.60,18.00,18.10,17787538.0,0.0,CRC
257,2127731,1.774976e+09,19.30,19.40,18.90,19.10,34822752.0,0.0,CRC
258,2127731,1.775063e+09,18.90,19.30,18.90,19.20,15691974.0,0.0,CRC
259,2127731,1.775149e+09,19.20,19.40,19.00,19.10,15953900.0,306664320.0,CRC

In [40]:
import pandas as pd

final_df['time'] = pd.to_datetime(final_df['time'], unit='s')

In [41]:
final_df['symbol'].value_counts()

symbol
2S       260
3BBIF    260
A        260
A5       260
AAI      260
        ...
CPT      260
BKA      230
88TH     121
ATLAS    111
ACAP      19
Name: count, Length: 197, dtype: int64

In [42]:
final_df.head()
final_df.tail()

,lastSequence,time,open,high,low,close,volume,value,symbol
255,2127731,2026-03-25 17:00:00,18.1,18.3,17.9,18.3,22095470.0,0.0,CRC
256,2127731,2026-03-26 17:00:00,18.4,18.6,18.0,18.1,17787538.0,0.0,CRC
257,2127731,2026-03-31 17:00:00,19.3,19.4,18.9,19.1,34822752.0,0.0,CRC
258,2127731,2026-04-01 17:00:00,18.9,19.3,18.9,19.2,15691974.0,0.0,CRC
259,2127731,2026-04-02 17:00:00,19.2,19.4,19.0,19.1,15953900.0,306664320.0,CRC

In [43]:
import pandas as pd

# แปลง Unix timestamp → datetime
final_df["date"] = pd.to_datetime(final_df["time"], unit="s")

# เรียงข้อมูลตาม หุ้น + วันที่
final_df = final_df.sort_values(["symbol", "date"])

final_df.head()

,lastSequence,time,open,high,low,close,volume,value,symbol,date
0,2306562,2025-03-05 17:00:00,2.26,2.26,2.20,2.26,48974.0,0.0,2S,2025-03-05 17:00:00
1,2306562,2025-03-06 17:00:00,2.14,2.20,2.10,2.18,82189.0,0.0,2S,2025-03-06 17:00:00
2,2306562,2025-03-09 17:00:00,2.12,2.16,2.12,2.16,329118.0,0.0,2S,2025-03-09 17:00:00
3,2306562,2025-03-10 17:00:00,2.18,2.22,2.14,2.20,126722.0,0.0,2S,2025-03-10 17:00:00
4,2306562,2025-03-11 17:00:00,2.18,2.22,2.16,2.20,35230.0,0.0,2S,2025-03-11 17:00:00

### ตรวจสอบว่าข้อมูลย้อนหลัง ~1 ปี

In [44]:
final_df.groupby("symbol")["date"].agg(["min", "max"])

                        min                 max
symbol
2S      2025-03-05 17:00:00 2026-04-02 17:00:00
3BBIF   2025-03-05 17:00:00 2026-04-02 17:00:00
88TH    2025-10-02 17:00:00 2026-04-02 17:00:00
A       2024-10-10 17:00:00 2026-02-25 17:00:00
A5      2025-02-27 17:00:00 2026-04-02 17:00:00
...                     ...                 ...
CPT     2025-02-23 17:00:00 2026-04-02 17:00:00
CPTREIT 2025-03-05 17:00:00 2026-04-02 17:00:00
CPW     2025-03-05 17:00:00 2026-04-02 17:00:00
CRANE   2025-03-05 17:00:00 2026-04-02 17:00:00
CRC     2025-03-05 17:00:00 2026-04-02 17:00:00

[197 rows x 2 columns]

### ตรวจสอบ Schema ของแต่ละ Table

In [45]:
import pandas as pd
from sqlalchemy import create_engine

In [47]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/thai_stock_market"
)

print("Connected to thai_stock_market")

Connected to thai_stock_market

In [48]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

tables_df = pd.read_sql(query, engine)
tables_df

   table_name
0  categories
1      stocks
2      prices

In [49]:
stocks_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'stocks';
""", engine)

stocks_schema

   column_name          data_type
0    div_yield            numeric
1          eps            numeric
2     stock_id            integer
3  category_id            integer
4           pe            numeric
5          pbv            numeric
6       symbol  character varying
7   stock_name               text

In [50]:
prices_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'prices';
""", engine)

prices_schema

  column_name data_type
0    price_id   integer
1    stock_id   integer
2  trade_date      date
3        open   numeric
4        high   numeric
5         low   numeric
6       close   numeric
7      volume    bigint
8  market_cap   numeric

In [51]:
pd.read_sql("SELECT COUNT(*) FROM stocks;", engine)

   count
0      0

In [52]:
pd.read_sql("SELECT COUNT(*) FROM prices;", engine)

   count
0      0

In [53]:
symbols_df = (
    final_df[['symbol']]
    .drop_duplicates()
    .reset_index(drop=True)
)

symbols_df

      symbol
0         2S
1      3BBIF
2       88TH
3          A
4         A5
..       ...
192      CPT
193  CPTREIT
194      CPW
195    CRANE
196      CRC

[197 rows x 1 columns]

### เชื่อมต่อ PostgreSQL

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/thai_stock_market"
)

print("DB Connected")

DB Connected

### Insert ข้อมูลลง table stocks

In [7]:
symbols = ["2S","3BBIF","88TH","A","A5","AAI","AAV","ABM","ACAP","ACC","ACE","ACG","ADB","ADD",
        "ADVANC","ADVICE","AE","AEONTS","AF","AFC","AGE","AH","AHC","AI","AIE","AIMCG","AIMIRT",
        "AIRA","AIT","AJ","AJA","AKP","AKR","AKS","ALLA","ALLY","ALPHAX","ALT","ALUCON","AMA",
        "AMANAH","AMARC","AMARIN","AMATA","AMATAR","AMATAV","AMC","AMR","ANAN","ANI","AOT","AP",
        "APCO","APCS","APO","APP","APURE","AQUA","ARIN","ARIP","ARROW","AS","ASAP","ASEFA","ASIA",
        "ASIAN","ASIMAR","ASK","ASN","ASP","ASW","ATLAS","ATP30","AU","AUCT","AURA","AWC","AXTRART",
        "AYUD","B","B52","BA","BAFS","BAM","BANPU","BAREIT","BAY","BBGI","BBIK","BBL","BC","BCH",
        "BCP","BCPG","BCT","BDMS","BE8","BEAUTY","BEC","BEM","BEYOND","BGC","BGRIM","BGT","BH",
        "BIG","BIOTEC","BIS","BIZ","BJC","BJCHI","BKA","BKD","BKGI","BKIH","BLA","BLAND","BLC",
        "BLESS","BLISS","BM","BOFFICE","BOL","BPP","BPS","BR","BRI","BROCK","BRR","BRRGIF","BSBM",
        "BSM","BTC","BTG","BTNC","BTS","BTSGIF","BTW","BUI","BVG","BWG","B-WORK","BYD","CAZ",
        "CBG","CCET","CCP","CEN","CENTEL","CEYE","CFARM","CFRESH","CGD","CGH","CH","CHAO",
        "CHARAN","CHASE","CHAYO","CHEWA","CHG","CHIC","CHO","CHOTI","CHOW","CI","CIG","CIMBT",
        "CITY","CIVIL","CK","CKP","CM","CMAN","CMC","CMO","CMR","CNT","COCOCO","COLOR","COM7",
        "COMAN","CPALL","CPANEL","CPAXT","CPF","CPH","CPI","CPL","CPN","CPNCG","CPNREIT","CPR",
        "CPT","CPTREIT","CPW","CRANE","CRC"]

In [8]:
import pandas as pd

symbols_df = pd.DataFrame({
    "symbol": symbols
})

In [9]:
symbols_df.head()

  symbol
0     2S
1  3BBIF
2   88TH
3      A
4     A5

In [10]:
symbols_df.to_sql(
    name="stocks",
    con=engine,
    if_exists="append",
    index=False
)

198

### Insert ราคาหุ้นย้อนหลัง 1 ปี → table prices

In [12]:
stocks_df = pd.read_sql(
    "SELECT stock_id, symbol FROM stocks;",
    engine
)

stocks_df

     stock_id   symbol
0           1       2S
1           2    3BBIF
2           3     88TH
3           4        A
4           5       A5
..        ...      ...
193       194      CPT
194       195  CPTREIT
195       196      CPW
196       197    CRANE
197       198      CRC

[198 rows x 2 columns]

In [16]:
from settrade_v2 import Investor

APP_ID = "BDYsxwFdwr4CGrqn"
APP_SECRET = "c/YrEWTsD6i7kfib8tF022qBrvNoNKh0jnUsqBtCurQ="
BROKER_ID = "SANDBOX"
APP_CODE = "SANDBOX"

investor = Investor(
    app_id=APP_ID,
    app_secret=APP_SECRET,
    broker_id=BROKER_ID,
    app_code=APP_CODE,
    is_auto_queue=False
)

market = investor.MarketData()

print("SETTRADE API connected, market ready")

SETTRADE API connected, market ready

In [17]:
import pandas as pd

# รายชื่อหุ้นที่ต้องการ
symbols = ["2S","3BBIF","88TH","A","A5","AAI","AAV","ABM","ACAP","ACC","ACE","ACG","ADB","ADD",
        "ADVANC","ADVICE","AE","AEONTS","AF","AFC","AGE","AH","AHC","AI","AIE","AIMCG","AIMIRT",
        "AIRA","AIT","AJ","AJA","AKP","AKR","AKS","ALLA","ALLY","ALPHAX","ALT","ALUCON","AMA",
        "AMANAH","AMARC","AMARIN","AMATA","AMATAR","AMATAV","AMC","AMR","ANAN","ANI","AOT","AP",
        "APCO","APCS","APO","APP","APURE","AQUA","ARIN","ARIP","ARROW","AS","ASAP","ASEFA","ASIA",
        "ASIAN","ASIMAR","ASK","ASN","ASP","ASW","ATLAS","ATP30","AU","AUCT","AURA","AWC","AXTRART",
        "AYUD","B","B52","BA","BAFS","BAM","BANPU","BAREIT","BAY","BBGI","BBIK","BBL","BC","BCH",
        "BCP","BCPG","BCT","BDMS","BE8","BEAUTY","BEC","BEM","BEYOND","BGC","BGRIM","BGT","BH",
        "BIG","BIOTEC","BIS","BIZ","BJC","BJCHI","BKA","BKD","BKGI","BKIH","BLA","BLAND","BLC",
        "BLESS","BLISS","BM","BOFFICE","BOL","BPP","BPS","BR","BRI","BROCK","BRR","BRRGIF","BSBM",
        "BSM","BTC","BTG","BTNC","BTS","BTSGIF","BTW","BUI","BVG","BWG","B-WORK","BYD","CAZ",
        "CBG","CCET","CCP","CEN","CENTEL","CEYE","CFARM","CFRESH","CGD","CGH","CH","CHAO",
        "CHARAN","CHASE","CHAYO","CHEWA","CHG","CHIC","CHO","CHOTI","CHOW","CI","CIG","CIMBT",
        "CITY","CIVIL","CK","CKP","CM","CMAN","CMC","CMO","CMR","CNT","COCOCO","COLOR","COM7",
        "COMAN","CPALL","CPANEL","CPAXT","CPF","CPH","CPI","CPL","CPN","CPNCG","CPNREIT","CPR",
        "CPT","CPTREIT","CPW","CRANE","CRC"]


all_prices = []

for symbol in symbols:
    print(f"Fetching {symbol} ...")
    
    data = market.get_candlestick(
        symbol=symbol,
        interval="1d",
        limit=260   # ประมาณ 1 ปีทำการ
    )
    
    df = pd.DataFrame(data)
    
    if not df.empty:
        df["symbol"] = symbol
        all_prices.append(df)

# รวมข้อมูลทุกหุ้นเป็น DataFrame เดียว
all_prices_df = pd.concat(all_prices, ignore_index=True)

print("Finished fetching all symbols")

Fetching 2S ...
Fetching 3BBIF ...
Fetching 88TH ...
Fetching A ...
Fetching A5 ...
Fetching AAI ...
Fetching AAV ...
Fetching ABM ...
Fetching ACAP ...
Fetching ACC ...
Fetching ACE ...
Fetching ACG ...
Fetching ADB ...
Fetching ADD ...
Fetching ADVANC ...
Fetching ADVICE ...
Fetching AE ...
Fetching AEONTS ...
Fetching AF ...
Fetching AFC ...
Fetching AGE ...
Fetching AH ...
Fetching AHC ...
Fetching AI ...
Fetching AIE ...
Fetching AIMCG ...
Fetching AIMIRT ...
Fetching AIRA ...
Fetching AIT ...
Fetching AJ ...
Fetching AJA ...
Fetching AKP ...
Fetching AKR ...
Fetching AKS ...
Fetching ALLA ...
Fetching ALLY ...
Fetching ALPHAX ...
Fetching ALT ...
Fetching ALUCON ...
Fetching AMA ...
Fetching AMANAH ...
Fetching AMARC ...
Fetching AMARIN ...
Fetching AMATA ...
Fetching AMATAR ...
Fetching AMATAV ...
Fetching AMC ...
Fetching AMR ...
Fetching ANAN ...
Fetching ANI ...
Fetching AOT ...
Fetching AP ...
Fetching APCO ...
Fetching APCS ...
Fetching APO ...
Fetching APP ...
Fetching APURE ...
Fetching AQUA ...
Fetching ARIN ...
Fetching ARIP ...
Fetching ARROW ...
Fetching AS ...
Fetching ASAP ...
Fetching ASEFA ...
Fetching ASIA ...
Fetching ASIAN ...
Fetching ASIMAR ...
Fetching ASK ...
Fetching ASN ...
Fetching ASP ...
Fetching ASW ...
Fetching ATLAS ...
Fetching ATP30 ...
Fetching AU ...
Fetching AUCT ...
Fetching AURA ...
Fetching AWC ...
Fetching AXTRART ...
Fetching AYUD ...
Fetching B ...
Fetching B52 ...
Fetching BA ...
Fetching BAFS ...
Fetching BAM ...
Fetching BANPU ...
Fetching BAREIT ...
Fetching BAY ...
Fetching BBGI ...
Fetching BBIK ...
Fetching BBL ...
Fetching BC ...
Fetching BCH ...
Fetching BCP ...
Fetching BCPG ...
Fetching BCT ...
Fetching BDMS ...
Fetching BE8 ...
Fetching BEAUTY ...
Fetching BEC ...
Fetching BEM ...
Fetching BEYOND ...
Fetching BGC ...
Fetching BGRIM ...
Fetching BGT ...
Fetching BH ...
Fetching BIG ...
Fetching BIOTEC ...
Fetching BIS ...
Fetching BIZ ...
Fetching BJC ...
Fetching BJCHI ...
Fetching BKA ...
Fetching BKD ...
Fetching BKGI ...
Fetching BKIH ...
Fetching BLA ...
Fetching BLAND ...
Fetching BLC ...
Fetching BLESS ...
Fetching BLISS ...
Fetching BM ...
Fetching BOFFICE ...
Fetching BOL ...
Fetching BPP ...
Fetching BPS ...
Fetching BR ...
Fetching BRI ...
Fetching BROCK ...
Fetching BRR ...
Fetching BRRGIF ...
Fetching BSBM ...
Fetching BSM ...
Fetching BTC ...
Fetching BTG ...
Fetching BTNC ...
Fetching BTS ...
Fetching BTSGIF ...
Fetching BTW ...
Fetching BUI ...
Fetching BVG ...
Fetching BWG ...
Fetching B-WORK ...
Fetching BYD ...
Fetching CAZ ...
Fetching CBG ...
Fetching CCET ...
Fetching CCP ...
Fetching CEN ...
Fetching CENTEL ...
Fetching CEYE ...
Fetching CFARM ...
Fetching CFRESH ...
Fetching CGD ...
Fetching CGH ...
Fetching CH ...
Fetching CHAO ...
Fetching CHARAN ...
Fetching CHASE ...
Fetching CHAYO ...
Fetching CHEWA ...
Fetching CHG ...
Fetching CHIC ...
Fetching CHO ...
Fetching CHOTI ...
Fetching CHOW ...
Fetching CI ...
Fetching CIG ...
Fetching CIMBT ...
Fetching CITY ...
Fetching CIVIL ...
Fetching CK ...
Fetching CKP ...
Fetching CM ...
Fetching CMAN ...
Fetching CMC ...
Fetching CMO ...
Fetching CMR ...
Fetching CNT ...
Fetching COCOCO ...
Fetching COLOR ...
Fetching COM7 ...
Fetching COMAN ...
Fetching CPALL ...
Fetching CPANEL ...
Fetching CPAXT ...
Fetching CPF ...
Fetching CPH ...
Fetching CPI ...
Fetching CPL ...
Fetching CPN ...
Fetching CPNCG ...
Fetching CPNREIT ...
Fetching CPR ...
Fetching CPT ...
Fetching CPTREIT ...
Fetching CPW ...
Fetching CRANE ...
Fetching CRC ...
Finished fetching all symbols

In [18]:
all_prices_df.head()

   lastSequence        time  open  high   low  close  volume  value symbol
0             0  1741194000  2.26  2.26  2.20   2.26   48974    0.0     2S
1             0  1741280400  2.14  2.20  2.10   2.18   82189    0.0     2S
2             0  1741539600  2.12  2.16  2.12   2.16  329118    0.0     2S
3             0  1741626000  2.18  2.22  2.14   2.20  126722    0.0     2S
4             0  1741712400  2.18  2.22  2.16   2.20   35230    0.0     2S

In [19]:
all_prices_df.shape

(50661, 9)

In [26]:
df["time"] = pd.to_datetime(df["time"], unit="s")
df["trade_date"] = df["time"].dt.date

In [27]:
df[["time","trade_date"]].head()

                 time  trade_date
0 2025-03-05 17:00:00  2025-03-05
1 2025-03-06 17:00:00  2025-03-06
2 2025-03-09 17:00:00  2025-03-09
3 2025-03-10 17:00:00  2025-03-10
4 2025-03-11 17:00:00  2025-03-11

In [28]:
df.dtypes

lastSequence             int64
time            datetime64[ns]
open                   float64
high                   float64
low                    float64
close                  float64
volume                   int64
value                    int64
symbol                  object
trade_date              object
dtype: object

In [34]:
all_prices_df.head()

   lastSequence        time  open  high   low  close  volume  value symbol
0             0  1741194000  2.26  2.26  2.20   2.26   48974    0.0     2S
1             0  1741280400  2.14  2.20  2.10   2.18   82189    0.0     2S
2             0  1741539600  2.12  2.16  2.12   2.16  329118    0.0     2S
3             0  1741626000  2.18  2.22  2.14   2.20  126722    0.0     2S
4             0  1741712400  2.18  2.22  2.16   2.20   35230    0.0     2S

In [35]:
#ดูทั้งหมด
all_prices_df

,lastSequence,time,open,high,low,close,volume,value,symbol
0,0,1741194000,2.26,2.26,2.20,2.26,48974,0.0,2S
1,0,1741280400,2.14,2.20,2.10,2.18,82189,0.0,2S
2,0,1741539600,2.12,2.16,2.12,2.16,329118,0.0,2S
3,0,1741626000,2.18,2.22,2.14,2.20,126722,0.0,2S
4,0,1741712400,2.18,2.22,2.16,2.20,35230,0.0,2S
...,...,...,...,...,...,...,...,...,...
50656,0,1774458000,18.10,18.30,17.90,18.30,22095470,0.0,CRC
50657,0,1774544400,18.40,18.60,18.00,18.10,17787538,0.0,CRC
50658,0,1774976400,19.30,19.40,18.90,19.10,34822752,0.0,CRC
50659,0,1775062800,18.90,19.30,18.90,19.20,15691974,0.0,CRC
50660,0,1775149200,19.30,19.60,19.20,19.40,12628610,0.0,CRC

In [36]:
print(all_prices_df["time"].head())   # ของเดิม
print(df["time"].head())             # หลังแปลง

0    1741194000
1    1741280400
2    1741539600
3    1741626000
4    1741712400
Name: time, dtype: int64
0   2025-03-05 17:00:00
1   2025-03-06 17:00:00
2   2025-03-09 17:00:00
3   2025-03-10 17:00:00
4   2025-03-11 17:00:00
Name: time, dtype: datetime64[ns]

In [37]:
df = all_prices_df.copy()

df["time"] = pd.to_datetime(df["time"], unit="s")

print(df["time"].head())

0   2025-03-05 17:00:00
1   2025-03-06 17:00:00
2   2025-03-09 17:00:00
3   2025-03-10 17:00:00
4   2025-03-11 17:00:00
Name: time, dtype: datetime64[ns]

In [38]:
df[["time"]].head()

                 time
0 2025-03-05 17:00:00
1 2025-03-06 17:00:00
2 2025-03-09 17:00:00
3 2025-03-10 17:00:00
4 2025-03-11 17:00:00

In [44]:
df.head()

,lastSequence,time,open,high,low,close,volume,value,symbol,stock_id,stock_name,category_id,pe,pbv,eps,div_yield
0,0,2025-03-05 17:00:00,2.26,2.26,2.20,2.26,48974,0.0,2S,1,None,None,None,None,None,None
1,0,2025-03-06 17:00:00,2.14,2.20,2.10,2.18,82189,0.0,2S,1,None,None,None,None,None,None
2,0,2025-03-09 17:00:00,2.12,2.16,2.12,2.16,329118,0.0,2S,1,None,None,None,None,None,None
3,0,2025-03-10 17:00:00,2.18,2.22,2.14,2.20,126722,0.0,2S,1,None,None,None,None,None,None
4,0,2025-03-11 17:00:00,2.18,2.22,2.16,2.20,35230,0.0,2S,1,None,None,None,None,None,None

In [45]:
df = all_prices_df.copy()

df["time"] = pd.to_datetime(df["time"], unit="s")
df["trade_date"] = df["time"].dt.date

stocks_df = pd.read_sql("SELECT * FROM stocks;", engine)
df = df.merge(stocks_df, on="symbol")

df = df.rename(columns={"id": "stock_id"})

df = df[[
    "stock_id",
    "trade_date",
    "open",
    "high",
    "low",
    "close",
    "volume"
]]

In [46]:
df.head()

   stock_id  trade_date  open  high   low  close  volume
0         1  2025-03-05  2.26  2.26  2.20   2.26   48974
1         1  2025-03-06  2.14  2.20  2.10   2.18   82189
2         1  2025-03-09  2.12  2.16  2.12   2.16  329118
3         1  2025-03-10  2.18  2.22  2.14   2.20  126722
4         1  2025-03-11  2.18  2.22  2.16   2.20   35230

## Insert ลง postgres table prices

In [50]:
#Insert ลง postgres table prices
df.to_sql(
    name="prices",
    con=engine,
    if_exists="append",
    index=False
)

661

In [51]:
pd.read_sql("SELECT * FROM prices LIMIT 5;", engine)

   price_id  stock_id  trade_date  open  high   low  close  volume market_cap
0         1         1  2025-03-05  2.26  2.26  2.20   2.26   48974       None
1         2         1  2025-03-06  2.14  2.20  2.10   2.18   82189       None
2         3         1  2025-03-09  2.12  2.16  2.12   2.16  329118       None
3         4         1  2025-03-10  2.18  2.22  2.14   2.20  126722       None
4         5         1  2025-03-11  2.18  2.22  2.16   2.20   35230       None

### INSERT ข้อมูลลง categories

In [57]:
import pandas as pd
from sqlalchemy import create_engine, text

In [58]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/thai_stock_market"
)

In [59]:
import pandas as pd

In [70]:
import pandas as pd

categories_df = pd.DataFrame({
    "category_id": [
        1,2,3,4,5,6,7,8,9,10,
        11,12,13,14,15,16,17,18,19,20
    ],
    "category_name": [
        "Agro & Food Industry",
        "Food & Beverage",
        "Energy & Utilities",
        "Banking",
        "Finance & Securities",
        "ICT",
        "Commerce",
        "Property Development",
        "Construction Services",
        "Construction Materials",
        "Transportation & Logistics",
        "Tourism & Leisure",
        "Health Care",
        "Media",
        "Packaging",
        "Industrial Materials & Machinery",
        "Automotive",
        "Insurance",
        "REIT & Property Fund",
        "MAI / Others"
    ]
})

categories_df

    category_id                     category_name
0             1              Agro & Food Industry
1             2                   Food & Beverage
2             3                Energy & Utilities
3             4                           Banking
4             5              Finance & Securities
5             6                               ICT
6             7                          Commerce
7             8              Property Development
8             9             Construction Services
9            10            Construction Materials
10           11        Transportation & Logistics
11           12                 Tourism & Leisure
12           13                       Health Care
13           14                             Media
14           15                         Packaging
15           16  Industrial Materials & Machinery
16           17                        Automotive
17           18                         Insurance
18           19              REIT & Property Fund
19           20                      MAI / Others

In [73]:
categories_df.to_sql(
    name="categories",
    con=engine,
    if_exists="append",
    index=False
)

print("Inserted categories")

Inserted categories

In [77]:
# map category จาก symbol
df["category"] = df["symbol"].map(mapping).fillna("MAI / Others")

# map เป็น category_id
category_id_map = dict(zip(categories_df["category_name"], categories_df["category_id"]))

df["category_id"] = df["category"].map(category_id_map)

df.head()

  symbol      category  category_id
0     2S  MAI / Others           20
1  3BBIF  MAI / Others           20
2   88TH  MAI / Others           20
3      A  MAI / Others           20
4     A5  MAI / Others           20

# ดึงชื่อบริษัทจริง 100% อัตโนมัติ”
👉 ใช้ yfinance (ข้อมูลจริงจากตลาด)
ใช้ data ที่มี (symbols list)

In [121]:
symbols = ["2S","3BBIF","88TH","A","A5","AAI","AAV","ABM","ACAP","ACC","ACE","ACG","ADB","ADD",
"ADVANC","ADVICE","AE","AEONTS","AF","AFC","AGE","AH","AHC","AI","AIE","AIMCG","AIMIRT",
"AIRA","AIT","AJ","AJA","AKP","AKR","AKS","ALLA","ALLY","ALPHAX","ALT","ALUCON","AMA",
"AMANAH","AMARC","AMARIN","AMATA","AMATAR","AMATAV","AMC","AMR","ANAN","ANI","AOT","AP",
"APCO","APCS","APO","APP","APURE","AQUA","ARIN","ARIP","ARROW","AS","ASAP","ASEFA","ASIA",
"ASIAN","ASIMAR","ASK","ASN","ASP","ASW","ATLAS","ATP30","AU","AUCT","AURA","AWC","AXTRART",
"AYUD","B","B52","BA","BAFS","BAM","BANPU","BAREIT","BAY","BBGI","BBIK","BBL","BC","BCH",
"BCP","BCPG","BCT","BDMS","BE8","BEAUTY","BEC","BEM","BEYOND","BGC","BGRIM","BGT","BH",
"BIG","BIOTEC","BIS","BIZ","BJC","BJCHI","BKA","BKD","BKGI","BKIH","BLA","BLAND","BLC",
"BLESS","BLISS","BM","BOFFICE","BOL","BPP","BPS","BR","BRI","BROCK","BRR","BRRGIF","BSBM",
"BSM","BTC","BTG","BTNC","BTS","BTSGIF","BTW","BUI","BVG","BWG","B-WORK","BYD","CAZ",
"CBG","CCET","CCP","CEN","CENTEL","CEYE","CFARM","CFRESH","CGD","CGH","CH","CHAO",
"CHARAN","CHASE","CHAYO","CHEWA","CHG","CHIC","CHO","CHOTI","CHOW","CI","CIG","CIMBT",
"CITY","CIVIL","CK","CKP","CM","CMAN","CMC","CMO","CMR","CNT","COCOCO","COLOR","COM7",
"COMAN","CPALL","CPANEL","CPAXT","CPF","CPH","CPI","CPL","CPN","CPNCG","CPNREIT","CPR",
"CPT","CPTREIT","CPW","CRANE","CRC"]

In [125]:
!pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [124]:
import yfinance as yf
import pandas as pd

data = []

for sym in symbols:
    try:
        ticker = yf.Ticker(sym + ".BK")  # หุ้นไทยต้องเติม .BK
        info = ticker.info
        name = info.get("longName") or info.get("shortName") or sym
        
        data.append({
            "symbol": sym,
            "stock_name": name
        })
    except:
        data.append({
            "symbol": sym,
            "stock_name": sym
        })

df = pd.DataFrame(data)
df

      symbol                                         stock_name
0         2S                    2S Metal Public Company Limited
1      3BBIF                   3BB Internet Infrastructure Fund
2       88TH                88(Thailand) Public Company Limited
3          A             Areeya Property Public Company Limited
4         A5            Asset Five Group Public Company Limited
5        AAI  Asian Alliance International Public Company Li...
6        AAV               Asia Aviation Public Company Limited
7        ABM                Asia Biomass Public Company Limited
8       ACAP          Asia Capital Group Public Company Limited
9        ACC  Advanced Connection Corporation Public Company...
10       ACE       Absolute Clean Energy Public Company Limited
11       ACG            Autocorp Holding Public Company Limited
12       ADB                  Applied DB Public Company Limited
13       ADD                 AddTech Hub Public Company Limited
14    ADVANC       Advanced Info Service Public Company Limited
15    ADVICE                          ADVICE_ADVICE IT INFINITE
16        AE      All Energy & Utilities Public Company Limited
17    AEONTS  AEON Thana Sinsap (Thailand) Public Company Li...
18        AF              AIRA Factoring Public Company Limited
19       AFC                  Asia Fiber Public Company Limited
20       AGE           Asia Green Energy Public Company Limited
21        AH               AAPICO Hitech Public Company Limited
22       AHC            Aikchol Hospital Public Company Limited
23        AI            Asian Insulators Public Company Limited
24       AIE                   AI Energy Public Company Limited
25     AIMCG  AIM Commercial Growth Freehold And Leasehold R...
26    AIMIRT  AIM Industrial Growth Freehold and Leasehold R...
27      AIRA                AIRA Capital Public Company Limited
28       AIT  Advanced Information Technology Public Company...
29        AJ                  A.J. Plast Public Company Limited
30       AJA       AJ Advance Technology Public Company Limited
31       AKP              Akkhie Prakarn Public Company Limited
32       AKR          Ekarat Engineering Public Company Limited
33       AKS             AKS Corporation Public Company Limited
34      ALLA                        Alla Public Company Limited
35      ALLY  Ally Freehold And Leasehold Real Estate Invest...
36    ALPHAX             Alpha Divisions Public Company Limited
37       ALT                 ALT Telecom Public Company Limited
38    ALUCON                      Alucon Public Company Limited
39       AMA                  Ama Marine Public Company Limited
40    AMANAH              Amanah Leasing Public Company Limited
41     AMARC  Asia Medical and Agricultural Laboratory and R...
42    AMARIN         Amarin Corporations Public Company Limited
43     AMATA           Amata Corporation Public Company Limited
44    AMATAR  Amata Summit Growth Freehold and Leasehold Rea...
45    AMATAV                    Amata VN Public Company Limited
46       AMC                  Asia Metal Public Company Limited
47       AMR                    AMR Asia Public Company Limited
48      ANAN          Ananda Development Public Company Limited
49       ANI                     ANI_ASIA NETWORK INTERNATIONAL
50       AOT        Airports of Thailand Public Company Limited
51        AP               AP (Thailand) Public Company Limited
52      APCO        Asian Phytoceuticals Public Company Limited
53      APCS              Asia Precision Public Company Limited
54       APO                                 APO_ASIAN PALM OIL
55       APP                    Applicad Public Company Limited
56     APURE           Agripure Holdings Public Company Limited
57      AQUA            Aqua Corporation Public Company Limited
58      ARIN               Arinsiri Land Public Company Limited
59      ARIP                        ARIP Public Company Limited
60     ARROW             Arrow Syndicate Public Company Limited
61        AS         Asphere Innovations Public Company Limited
62      ASAP  Synergetic Auto Performance Public Company Lim...
63     ASEFA                       Asefa Public Company Limited
64      ASIA                  Asia Hotel Public Company Limited
65     ASIAN       Asian Sea Corporation Public Company Limited
66    ASIMAR       Asian Marine Services Public Company Limited
67       ASK        Asia Sermkij Leasing Public Company Limited
68       ASN                  ASN Broker Public Company Limited
69       ASP    Asia Plus Group Holdings Public Company Limited
70       ASW                   Assetwise Public Company Limited
71     ATLAS                                 ATLAS_ATLAS ENERGY
72     ATP30                      ATP 30 Public Company Limited
73        AU                   After You Public Company Limited
74      AUCT               Union Auction Public Company Limited
75      AURA               Aurora Design Public Company Limited
76       AWC            Asset World Corp Public Company Limited
77   AXTRART  Axtra Future City Freehold And Leasehold Real ...
78      AYUD     Allianz Ayudhya Capital Public Company Limited
79         B                   Begistics Public Company Limited
80       B52                B-52 Capital Public Company Limited
81        BA             Bangkok Airways Public Company Limited
82      BAFS  Bangkok Aviation Fuel Services Public Company ...
83       BAM  Bangkok Commercial Asset Management Public Com...
84     BANPU                       Banpu Public Company Limited
85    BAREIT  BA Airport Leasehold Real Estate Investment Trust
86       BAY             Bank of Ayudhya Public Company Limited
87      BBGI                        BBGI Public Company Limited
88      BBIK               Bluebik Group Public Company Limited
89       BBL                Bangkok Bank Public Company Limited
90        BC        Boutique Corporation Public Company Limited
91       BCH      Bangkok Chain Hospital Public Company Limited
92       BCP        Bangchak Corporation Public Company Limited
93      BCPG                        BCPG Public Company Limited
94       BCT     Birla Carbon (Thailand) Public Company Limited
95      BDMS  Bangkok Dusit Medical Services Public Company ...
96       BE8                Beryl 8 Plus Public Company Limited
97    BEAUTY            Beauty Community Public Company Limited
98       BEC                   BEC World Public Company Limited
99       BEM  Bangkok Expressway and Metro Public Company Li...
100   BEYOND            Bound and Beyond Public Company Limited
101      BGC          BG Container Glass Public Company Limited
102    BGRIM               B.Grimm Power Public Company Limited
103      BGT             BGT Corporation Public Company Limited
104       BH         Bumrungrad Hospital Public Company Limited
105      BIG      Big Camera Corporation Public Company Limited
106   BIOTEC       Bio Green Energy Tech Public Company Limited
107      BIS    Bioscience Animal Health Public Company Limited
108      BIZ          Business Alignment Public Company Limited
109      BJC                Berli Jucker Public Company Limited
110    BJCHI        BJC Heavy Industries Public Company Limited
111      BKA                       BKA_BANGKOK ASSET INTERGROUP
112      BKD                                     Buakaew Income
113     BKGI  Bangkok Genomics Innovation Public Company Lim...
114     BKIH                BKI Holdings Public Company Limited
115      BLA      Bangkok Life Assurance Public Company Limited
116    BLAND                Bangkok Land Public Company Limited
117      BLC    Bangkok Lab And Cosmetic Public Company Limited
118    BLESS           Bless Asset Group Public Company Limited
119    BLISS          Bliss Intelligence Public Company Limited
120       BM         Bangkok Sheet Metal Public Company Limited
121  BOFFICE  Bhiraj Office Leasehold Real Estate Investment...
122      BOL             Business Online Public Company Limited
123      BPP                 Banpu Power Public Company Limited
124      BPS                                 BPS_BPS TECHNOLOGY
125       BR               Bangkok Ranch Public Company Limited
126      BRI                    Britania Public Company Limited
127    BROCK            Baan Rock Garden Public Company Limited
128      BRR               Buriram Sugar Public Company Limited
129   BRRGIF  Buriram Sugar Group Power Plant Infrastructure...
130     BSBM          Bangsaphan Barmill Public Company Limited
131      BSM                BuilderSmart Public Company Limited
132      BTC           The Brooker Group Public Company Limited
133      BTG                     Betagro Public Company Limited
134     BTNC            Boutique Newcity Public Company Limited
135      BTS          BTS Group Holdings Public Company Limited
136   BTSGIF   BTS Rail Mass Transit Growth Infrastructure Fund
137      BTW        BT Wealth Industries Public Company Limited
138      BUI     Bangkok Union Insurance Public Company Limited
139      BVG           BlueVenture Group Public Company Limited
140      BWG          Better World Green Public Company Limited
141   B-WORK  Bualuang Office Leasehold Real Estate Investme...
142      BYD           Beyond Securities Public Company Limited
143      CAZ              CAZ (Thailand) Public Company Limited
144      CBG               Carabao Group Public Company Limited
145     CCET  Cal-Comp Electronics (Thailand) Public Company...
146      CCP   Chonburi Concrete Product Public Company Limited
147      CEN  Capital Engineering Network Public Company Lim...
148   CENTEL         Central Plaza Hotel Public Company Limited
149     CEYE                Chamni's Eye Public Company Limited
150    CFARM          Chuwit Farm (2019) Public Company Limited
151   CFRESH           Seafresh Industry Public Company Limited
152      CGD   Country Group Development Public Company Limited
153      CGH      Country Group Holdings Public Company Limited
154       CH                   Chin Huay Public Company Limited
155     CHAO                        CHAO_CHAOSUA FOODS INDUSTRY
156   CHARAN            Charan Insurance Public Company Limited
157    CHASE                  Chase Asia Public Company Limited
158    CHAYO                 Chayo Group Public Company Limited
159    CHEWA                   Chewathai Public Company Limited
160      CHG           Chularat Hospital Public Company Limited
161     CHIC               Chic Republic Public Company Limited
162      CHO                  Cho Thavee Public Company Limited
163    CHOTI  Kiang Huat Sea Gull Trading Frozen Food Public...
164     CHOW       Chow Bright Ventures Holdings Public Company
165       CI    Charn Issara Development Public Company Limited
166      CIG                  C.I. Group Public Company Limited
167    CIMBT              CIMB Thai Bank Public Company Limited
168     CITY                  City Steel Public Company Limited
169    CIVIL           Civil Engineering Public Company Limited
170       CK               CH. Karnchang Public Company Limited
171      CKP                    CK Power Public Company Limited
172       CM      Chiangmai Frozen Foods Public Company Limited
173     CMAN                    Chememan Public Company Limited
174      CMC         Chaoprayamahanakorn Public Company Limited
175      CMO                         CMO Public Company Limited
176      CMR  Chiang Mai Ram Medical Business Public Company...
177      CNT  Christiani & Nielsen (Thai) Public Company Lim...
178   COCOCO                Thai Coconut Public Company Limited
179    COLOR                Salee Colour Public Company Limited
180     COM7                        Com7 Public Company Limited
181    COMAN      Comanche International Public Company Limited
182    CPALL                      CP ALL Public Company Limited
183   CPANEL                      CPanel Public Company Limited
184    CPAXT                    CP Axtra Public Company Limited
185      CPF      Charoen Pokphand Foods Public Company Limited
186      CPH        Castle Peak Holdings Public Company Limited
187      CPI  Chumporn Palm Oil Industry Public Company Limited
188      CPL                   CPL Group Public Company Limited
189      CPN             Central Pattana Public Company Limited
190    CPNCG      CPN Commercial Growth Leasehold Property Fund
191  CPNREIT                   CPN Retail Growth Leasehold REIT
192      CPR         CPR Gomu Industrial Public Company Limited
193      CPT        CPT Drives and Power Public Company Limited
194  CPTREIT  C.P. Tower Leasehold Real Estate Investment Trust
195      CPW                 Copperwired Public Company Limited
196    CRANE                      Chukai Public Company Limited
197      CRC  Central Retail Corporation Public Company Limited

In [107]:
df.head()

  symbol                               stock_name
0     2S          2S Metal Public Company Limited
1  3BBIF         3BB Internet Infrastructure Fund
2   88TH      88(Thailand) Public Company Limited
3      A   Areeya Property Public Company Limited
4     A5  Asset Five Group Public Company Limited

## เชื่อมต่อ Postgres

In [123]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/thai_stock_market"
)

In [109]:
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in df.iterrows():
        conn.execute(text("""
            INSERT INTO stocks (symbol, stock_name)
            VALUES (:symbol, :stock_name)
            ON CONFLICT (symbol)
            DO UPDATE SET
                stock_name = EXCLUDED.stock_name
        """), {
            "symbol": row["symbol"],
            "stock_name": row["stock_name"]
        })

print("✅ Upsert completed (no duplicate error)")

✅ Upsert completed (no duplicate error)

## ตรวจสอบ

In [126]:
pd.read_sql("SELECT * FROM stocks ORDER BY symbol", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20,None,None,None,None
1,2,3BBIF,3BB Internet Infrastructure Fund,20,None,None,None,None
2,3,88TH,88(Thailand) Public Company Limited,20,None,None,None,None
3,4,A,Areeya Property Public Company Limited,20,None,None,None,None
4,5,A5,Asset Five Group Public Company Limited,20,None,None,None,None
5,6,AAI,Asian Alliance International Public Company Li...,20,None,None,None,None
6,7,AAV,Asia Aviation Public Company Limited,11,None,None,None,None
7,8,ABM,Asia Biomass Public Company Limited,20,None,None,None,None
8,9,ACAP,Asia Capital Group Public Company Limited,20,None,None,None,None
9,10,ACC,Advanced Connection Corporation Public Company...,20,None,None,None,None
10,11,ACE,Absolute Clean Energy Public Company Limited,3,None,None,None,None
11,12,ACG,Autocorp Holding Public Company Limited,20,None,None,None,None
12,13,ADB,Applied DB Public Company Limited,20,None,None,None,None
13,14,ADD,AddTech Hub Public Company Limited,20,None,None,None,None
14,15,ADVANC,Advanced Info Service Public Company Limited,6,None,None,None,None
15,16,ADVICE,ADVICE_ADVICE IT INFINITE,20,None,None,None,None
16,17,AE,All Energy & Utilities Public Company Limited,20,None,None,None,None
17,18,AEONTS,AEON Thana Sinsap (Thailand) Public Company Li...,5,None,None,None,None
18,19,AF,AIRA Factoring Public Company Limited,20,None,None,None,None
19,20,AFC,Asia Fiber Public Company Limited,20,None,None,None,None
20,21,AGE,Asia Green Energy Public Company Limited,3,None,None,None,None
21,22,AH,AAPICO Hitech Public Company Limited,20,None,None,None,None
22,23,AHC,Aikchol Hospital Public Company Limited,20,None,None,None,None
23,24,AI,Asian Insulators Public Company Limited,20,None,None,None,None
24,25,AIE,AI Energy Public Company Limited,20,None,None,None,None
25,26,AIMCG,AIM Commercial Growth Freehold And Leasehold R...,20,None,None,None,None
26,27,AIMIRT,AIM Industrial Growth Freehold and Leasehold R...,20,None,None,None,None
27,28,AIRA,AIRA Capital Public Company Limited,20,None,None,None,None
28,29,AIT,Advanced Information Technology Public Company...,6,None,None,None,None
29,30,AJ,A.J. Plast Public Company Limited,20,None,None,None,None
30,31,AJA,AJ Advance Technology Public Company Limited,20,None,None,None,None
31,32,AKP,Akkhie Prakarn Public Company Limited,20,None,None,None,None
32,33,AKR,Ekarat Engineering Public Company Limited,20,None,None,None,None
33,34,AKS,AKS Corporation Public Company Limited,20,None,None,None,None
34,35,ALLA,Alla Public Company Limited,20,None,None,None,None
35,36,ALLY,Ally Freehold And Leasehold Real Estate Invest...,20,None,None,None,None
36,37,ALPHAX,Alpha Divisions Public Company Limited,20,None,None,None,None
37,38,ALT,ALT Telecom Public Company Limited,6,None,None,None,None
38,39,ALUCON,Alucon Public Company Limited,20,None,None,None,None
39,40,AMA,Ama Marine Public Company Limited,20,None,None,None,None
40,41,AMANAH,Amanah Leasing Public Company Limited,5,None,None,None,None
41,42,AMARC,Asia Medical and Agricultural Laboratory and R...,20,None,None,None,None
42,43,AMARIN,Amarin Corporations Public Company Limited,20,None,None,None,None
43,44,AMATA,Amata Corporation Public Company Limited,8,None,None,None,None
44,45,AMATAR,Amata Summit Growth Freehold and Leasehold Rea...,20,None,None,None,None
45,46,AMATAV,Amata VN Public Company Limited,8,None,None,None,None
46,47,AMC,Asia Metal Public Company Limited,20,None,None,None,None
47,48,AMR,AMR Asia Public Company Limited,20,None,None,None,None
48,49,ANAN,Ananda Development Public Company Limited,8,None,None,None,None
49,50,ANI,ANI_ASIA NETWORK INTERNATIONAL,20,None,None,None,None
50,51,AOT,Airports of Thailand Public Company Limited,11,None,None,None,None
51,52,AP,AP (Thailand) Public Company Limited,8,None,None,None,None
52,53,APCO,Asian Phytoceuticals Public Company Limited,20,None,None,None,None
53,54,APCS,Asia Precision Public Company Limited,20,None,None,None,None
54,55,APO,APO_ASIAN PALM OIL,20,None,None,None,None
55,56,APP,Applicad Public Company Limited,20,None,None,None,None
56,57,APURE,Agripure Holdings Public Company Limited,20,None,None,None,None
57,58,AQUA,Aqua Corporation Public Company Limited,20,None,None,None,None
58,59,ARIN,Arinsiri Land Public Company Limited,20,None,None,None,None
59,60,ARIP,ARIP Public Company Limited,20,None,None,None,None
60,61,ARROW,Arrow Syndicate Public Company Limited,20,None,None,None,None
61,62,AS,Asphere Innovations Public Company Limited,20,None,None,None,None
62,63,ASAP,Synergetic Auto Performance Public Company Lim...,20,None,None,None,None
63,64,ASEFA,Asefa Public Company Limited,20,None,None,None,None
64,65,ASIA,Asia Hotel Public Company Limited,20,None,None,None,None
65,66,ASIAN,Asian Sea Corporation Public Company Limited,20,None,None,None,None
66,67,ASIMAR,Asian Marine Services Public Company Limited,11,None,None,None,None
67,68,ASK,Asia Sermkij Leasing Public Company Limited,5,None,None,None,None
68,69,ASN,ASN Broker Public Company Limited,20,None,None,None,None
69,70,ASP,Asia Plus Group Holdings Public Company Limited,5,None,None,None,None
70,71,ASW,Assetwise Public Company Limited,20,None,None,None,None
71,72,ATLAS,ATLAS_ATLAS ENERGY,20,None,None,None,None
72,73,ATP30,ATP 30 Public Company Limited,11,None,None,None,None
73,74,AU,After You Public Company Limited,20,None,None,None,None
74,75,AUCT,Union Auction Public Company Limited,20,None,None,None,None
75,76,AURA,Aurora Design Public Company Limited,20,None,None,None,None
76,77,AWC,Asset World Corp Public Company Limited,8,None,None,None,None
77,78,AXTRART,Axtra Future City Freehold And Leasehold Real ...,20,None,None,None,None
78,79,AYUD,Allianz Ayudhya Capital Public Company Limited,20,None,None,None,None
79,80,B,Begistics Public Company Limited,20,None,None,None,None
80,142,B-WORK,Bualuang Office Leasehold Real Estate Investme...,20,None,None,None,None
81,81,B52,B-52 Capital Public Company Limited,20,None,None,None,None
82,82,BA,Bangkok Airways Public Company Limited,11,None,None,None,None
83,83,BAFS,Bangkok Aviation Fuel Services Public Company ...,11,None,None,None,None
84,84,BAM,Bangkok Commercial Asset Management Public Com...,5,None,None,None,None
85,85,BANPU,Banpu Public Company Limited,3,None,None,None,None
86,86,BAREIT,BA Airport Leasehold Real Estate Investment Trust,20,None,None,None,None
87,87,BAY,Bank of Ayudhya Public Company Limited,4,None,None,None,None
88,88,BBGI,BBGI Public Company Limited,20,None,None,None,None
89,89,BBIK,Bluebik Group Public Company Limited,6,None,None,None,None
90,90,BBL,Bangkok Bank Public Company Limited,4,None,None,None,None
91,91,BC,Boutique Corporation Public Company Limited,20,None,None,None,None
92,92,BCH,Bangkok Chain Hospital Public Company Limited,20,None,None,None,None
93,93,BCP,Bangchak Corporation Public Company Limited,3,None,None,None,None
94,94,BCPG,BCPG Public Company Limited,3,None,None,None,None
95,95,BCT,Birla Carbon (Thailand) Public Company Limited,20,None,None,None,None
96,96,BDMS,Bangkok Dusit Medical Services Public Company ...,13,None,None,None,None
97,97,BE8,Beryl 8 Plus Public Company Limited,6,None,None,None,None
98,98,BEAUTY,Beauty Community Public Company Limited,20,None,None,None,None
99,99,BEC,BEC World Public Company Limited,20,None,None,None,None
100,100,BEM,Bangkok Expressway and Metro Public Company Li...,11,None,None,None,None
101,101,BEYOND,Bound and Beyond Public Company Limited,20,None,None,None,None
102,102,BGC,BG Container Glass Public Company Limited,20,None,None,None,None
103,103,BGRIM,B.Grimm Power Public Company Limited,3,None,None,None,None
104,104,BGT,BGT Corporation Public Company Limited,20,None,None,None,None
105,105,BH,Bumrungrad Hospital Public Company Limited,13,None,None,None,None
106,106,BIG,Big Camera Corporation Public Company Limited,20,None,None,None,None
107,107,BIOTEC,Bio Green Energy Tech Public Company Limited,20,None,None,None,None
108,108,BIS,Bioscience Animal Health Public Company Limited,20,None,None,None,None
109,109,BIZ,Business Alignment Public Company Limited,20,None,None,None,None
110,110,BJC,Berli Jucker Public Company Limited,7,None,None,None,None
111,111,BJCHI,BJC Heavy Industries Public Company Limited,20,None,None,None,None
112,112,BKA,BKA_BANGKOK ASSET INTERGROUP,20,None,None,None,None
113,113,BKD,Buakaew Income,20,None,None,None,None
114,114,BKGI,Bangkok Genomics Innovation Public Company Lim...,20,None,None,None,None
115,115,BKIH,BKI Holdings Public Company Limited,20,None,None,None,None
116,116,BLA,Bangkok Life Assurance Public Company Limited,20,None,None,None,None
117,117,BLAND,Bangkok Land Public Company Limited,20,None,None,None,None
118,118,BLC,Bangkok Lab And Cosmetic Public Company Limited,20,None,None,None,None
119,119,BLESS,Bless Asset Group Public Company Limited,20,None,None,None,None
120,120,BLISS,Bliss Intelligence Public Company Limited,20,None,None,None,None
121,121,BM,Bangkok Sheet Metal Public Company Limited,20,None,None,None,None
122,122,BOFFICE,Bhiraj Office Leasehold Real Estate Investment...,20,None,None,None,None
123,123,BOL,Business Online Public Company Limited,20,None,None,None,None
124,124,BPP,Banpu Power Public Company Limited,3,None,None,None,None
125,125,BPS,BPS_BPS TECHNOLOGY,20,None,None,None,None
126,126,BR,Bangkok Ranch Public Company Limited,20,None,None,None,None
127,127,BRI,Britania Public Company Limited,20,None,None,None,None
128,128,BROCK,Baan Rock Garden Public Company Limited,20,None,None,None,None
129,129,BRR,Buriram Sugar Public Company Limited,20,None,None,None,None
130,130,BRRGIF,Buriram Sugar Group Power Plant Infrastructure...,20,None,None,None,None
131,131,BSBM,Bangsaphan Barmill Public Company Limited,20,None,None,None,None
132,132,BSM,BuilderSmart Public Company Limited,20,None,None,None,None
133,133,BTC,The Brooker Group Public Company Limited,20,None,None,None,None
134,134,BTG,Betagro Public Company Limited,2,None,None,None,None
135,135,BTNC,Boutique Newcity Public Company Limited,20,None,None,None,None
136,136,BTS,BTS Group Holdings Public Company Limited,11,None,None,None,None
137,137,BTSGIF,BTS Rail Mass Transit Growth Infrastructure Fund,11,None,None,None,None
138,138,BTW,BT Wealth Industries Public Company Limited,20,None,None,None,None
139,139,BUI,Bangkok Union Insurance Public Company Limited,20,None,None,None,None
140,140,BVG,BlueVenture Group Public Company Limited,20,None,None,None,None
141,141,BWG,Better World Green Public Company Limited,20,None,None,None,None
142,143,BYD,Beyond Securities Public Company Limited,20,None,None,None,None
143,144,CAZ,CAZ (Thailand) Public Company Limited,20,None,None,None,None
144,145,CBG,Carabao Group Public Company Limited,2,None,None,None,None
145,146,CCET,Cal-Comp Electronics (Thailand) Public Company...,20,None,None,None,None
146,147,CCP,Chonburi Concrete Product Public Company Limited,20,None,None,None,None
147,148,CEN,Capital Engineering Network Public Company Lim...,20,None,None,None,None
148,149,CENTEL,Central Plaza Hotel Public Company Limited,12,None,None,None,None
149,150,CEYE,Chamni's Eye Public Company Limited,20,None,None,None,None
150,151,CFARM,Chuwit Farm (2019) Public Company Limited,20,None,None,None,None
151,152,CFRESH,Seafresh Industry Public Company Limited,20,None,None,None,None
152,153,CGD,Country Group Development Public Company Limited,20,None,None,None,None
153,154,CGH,Country Group Holdings Public Company Limited,20,None,None,None,None
154,155,CH,Chin Huay Public Company Limited,20,None,None,None,None
155,156,CHAO,CHAO_CHAOSUA FOODS INDUSTRY,20,None,None,None,None
156,157,CHARAN,Charan Insurance Public Company Limited,20,None,None,None,None
157,158,CHASE,Chase Asia Public Company Limited,20,None,None,None,None
158,159,CHAYO,Chayo Group Public Company Limited,5,None,None,None,None
159,160,CHEWA,Chewathai Public Company Limited,20,None,None,None,None
160,161,CHG,Chularat Hospital Public Company Limited,13,None,None,None,None
161,162,CHIC,Chic Republic Public Company Limited,20,None,None,None,None
162,163,CHO,Cho Thavee Public Company Limited,20,None,None,None,None
163,164,CHOTI,Kiang Huat Sea Gull Trading Frozen Food Public...,20,None,None,None,None
164,165,CHOW,Chow Bright Ventures Holdings Public Company,20,None,None,None,None
165,166,CI,Charn Issara Development Public Company Limited,20,None,None,None,None
166,167,CIG,C.I. Group Public Company Limited,20,None,None,None,None
167,168,CIMBT,CIMB Thai Bank Public Company Limited,4,None,None,None,None
168,169,CITY,City Steel Public Company Limited,20,None,None,None,None
169,170,CIVIL,Civil Engineering Public Company Limited,9,None,None,None,None
170,171,CK,CH. Karnchang Public Company Limited,9,None,None,None,None
171,172,CKP,CK Power Public Company Limited,3,None,None,None,None
172,173,CM,Chiangmai Frozen Foods Public Company Limited,20,None,None,None,None
173,174,CMAN,Chememan Public Company Limited,20,None,None,None,None
174,175,CMC,Chaoprayamahanakorn Public Company Limited,20,None,None,None,None
175,176,CMO,CMO Public Company Limited,20,None,None,None,None
176,177,CMR,Chiang Mai Ram Medical Business Public Company...,20,None,None,None,None
177,178,CNT,Christiani & Nielsen (Thai) Public Company Lim...,9,None,None,None,None
178,179,COCOCO,Thai Coconut Public Company Limited,20,None,None,None,None
179,180,COLOR,Salee Colour Public Company Limited,20,None,None,None,None
180,181,COM7,Com7 Public Company Limited,6,None,None,None,None
181,182,COMAN,Comanche International Public Company Limited,6,None,None,None,None
182,183,CPALL,CP ALL Public Company Limited,7,None,None,None,None
183,184,CPANEL,CPanel Public Company Limited,20,None,None,None,None
184,185,CPAXT,CP Axtra Public Company Limited,7,None,None,None,None
185,186,CPF,Charoen Pokphand Foods Public Company Limited,2,None,None,None,None
186,187,CPH,Castle Peak Holdings Public Company Limited,20,None,None,None,None
187,188,CPI,Chumporn Palm Oil Industry Public Company Limited,20,None,None,None,None
188,189,CPL,CPL Group Public Company Limited,20,None,None,None,None
189,190,CPN,Central Pattana Public Company Limited,8,None,None,None,None
190,191,CPNCG,CPN Commercial Growth Leasehold Property Fund,20,None,None,None,None
191,192,CPNREIT,CPN Retail Growth Leasehold REIT,20,None,None,None,None
192,193,CPR,CPR Gomu Industrial Public Company Limited,20,None,None,None,None
193,194,CPT,CPT Drives and Power Public Company Limited,20,None,None,None,None
194,195,CPTREIT,C.P. Tower Leasehold Real Estate Investment Trust,20,None,None,None,None
195,196,CPW,Copperwired Public Company Limited,6,None,None,None,None
196,197,CRANE,Chukai Public Company Limited,20,None,None,None,None
197,198,CRC,Central Retail Corporation Public Company Limited,7,None,None,None,None

# ดึงครั้งที่ 2