In [1]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.3)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (44.0.1)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.12.2)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=37.0->settrade-v2) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2025.8.3)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [2]:
#import และตั้งค่า Credential
from settrade_v2 import Investor
from pprint import pprint

In [10]:
from settrade_v2 import Investor

APP_ID = "BDYsxwFdwr4CGrqn"
APP_SECRET = "c/YrEWTsD6i7kfib8tF022qBrvNoNKh0jnUsqBtCurQ="
BROKER_ID = "SANDBOX"
APP_CODE = "SANDBOX"

investor = Investor(
    app_id=APP_ID,
    app_secret=APP_SECRET,
    broker_id=BROKER_ID,
    app_code=APP_CODE,
    is_auto_queue=False
)

print("API Connected")

HTTPError: 503 Server Error: Service Unavailable for url: https://open-api-test.settrade.com/sdk-open-api/sdk-version.json

 ### ❌ Server ของ SETTRADE (sandbox) ใช้งานไม่ได้ตอนนี้ HTTPError: 503 Service Unavailable

# 📊 Stock Data Pipeline (YFinance → PostgreSQL)

## 🎯 Objective
ดึงข้อมูลหุ้นย้อนหลัง 1 ปี จาก Yahoo Finance และบันทึกลง PostgreSQL

---
```python
!pip install yfinance pandas sqlalchemy psycopg2-binary

In [11]:
!pip install yfinance pandas sqlalchemy psycopg2-binary

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [12]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
import time

## เชื่อม PostgreSQL

In [17]:
engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")
print ('เชื่อมต่อ')

เชื่อมต่อ

In [18]:
tickers = [
"LH","LHFG","LHHOTEL","LHK","LHRREIT","LHSC","LIT","LOXLEY","LPH","LPN",
"LRH","LST","LTMH","LTS","LUXF","M","MADAME","MAGURO","MAJOR","MALEE",
"MANRIN","MASTEC","MASTER","MATCH","MATI","MBAX","MBK","MC","MCA","M-CHAI",
"MCOT","MCS","MDX","MEB","MEDEZE","MEGA","MENA","META","METCO","MFC",
"MFEC","MGC","MGI","MGT","MICRO","MIDA","MII","MILL","MINT","MIPF",
"MITSIB","MJD","MJLF","MK","ML","MMM","MNIT","MNIT2","MNRF","MODERN",
"MONO","MOONG","MORE","MOSHI","MOTHER","M-PAT","MPJ","MRDIYT","MSC","MST",
"M-STOR","MTC","MTI","MTW","MUD","MVP","NAM","NAT","NATION","NC",
"NCAP","NCH","NCL","NCP","NDR","NEO","NEP","NER","NETBAY","NEW",
"NEX","NFC","NKI","NKT","NL","NNCL","NOBLE","NOVA","NPK","NRF"
]

df_stocks = pd.DataFrame({"symbol": tickers})

## ใส่ลง table stocks

In [19]:
df_stocks.to_sql("stocks", engine, if_exists="append", index=False)

100

In [35]:
#เช็คว่าเข้าแล้ว
pd.read_sql("SELECT * FROM stocks LIMIT 10", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,807,LH,None,NaN,None,None,None,None
1,808,LHFG,None,NaN,None,None,None,None
2,809,LHHOTEL,None,NaN,None,None,None,None
3,1,2S,2S Metal Public Company Limited,20.0,None,None,None,None
4,2,3BBIF,3BB Internet Infrastructure Fund,20.0,None,None,None,None
5,3,88TH,88(Thailand) Public Company Limited,20.0,None,None,None,None
6,4,A,Areeya Property Public Company Limited,20.0,None,None,None,None
7,5,A5,Asset Five Group Public Company Limited,20.0,None,None,None,None
8,6,AAI,Asian Alliance International Public Company Li...,20.0,None,None,None,None
9,7,AAV,Asia Aviation Public Company Limited,11.0,None,None,None,None

## โหลดข้อมูลหุ้น “ย้อนหลัง 1 ปีจากวันนี้” → ใช้ period="1y"

In [21]:
# เติม .BK
tickers_yf = [t + ".BK" for t in tickers]

data = yf.download(
    tickers_yf,
    period="1y",
    group_by="ticker",
    progress=False
)

In [22]:
#ดูชื่อหุ้นที่โหลดได้
data.columns.levels[0]

Index(['LH.BK', 'LHFG.BK', 'LHHOTEL.BK', 'LHK.BK', 'LHRREIT.BK', 'LHSC.BK',
       'LIT.BK', 'LOXLEY.BK', 'LPH.BK', 'LPN.BK', 'LRH.BK', 'LST.BK',
       'LTMH.BK', 'LTS.BK', 'LUXF.BK', 'M-CHAI.BK', 'M-PAT.BK', 'M-STOR.BK',
       'M.BK', 'MADAME.BK', 'MAGURO.BK', 'MAJOR.BK', 'MALEE.BK', 'MANRIN.BK',
       'MASTEC.BK', 'MASTER.BK', 'MATCH.BK', 'MATI.BK', 'MBAX.BK', 'MBK.BK',
       'MC.BK', 'MCA.BK', 'MCOT.BK', 'MCS.BK', 'MDX.BK', 'MEB.BK', 'MEDEZE.BK',
       'MEGA.BK', 'MENA.BK', 'META.BK', 'METCO.BK', 'MFC.BK', 'MFEC.BK',
       'MGC.BK', 'MGI.BK', 'MGT.BK', 'MICRO.BK', 'MIDA.BK', 'MII.BK',
       'MILL.BK', 'MINT.BK', 'MIPF.BK', 'MITSIB.BK', 'MJD.BK', 'MJLF.BK',
       'MK.BK', 'ML.BK', 'MMM.BK', 'MNIT.BK', 'MNIT2.BK', 'MNRF.BK',
       'MODERN.BK', 'MONO.BK', 'MOONG.BK', 'MORE.BK', 'MOSHI.BK', 'MOTHER.BK',
       'MPJ.BK', 'MRDIYT.BK', 'MSC.BK', 'MST.BK', 'MTC.BK', 'MTI.BK', 'MTW.BK',
       'MUD.BK', 'MVP.BK', 'NAM.BK', 'NAT.BK', 'NATION.BK', 'NC.BK', 'NCAP.BK',
       'NCH.BK', 'NCL.BK', 'NCP.BK', 'NDR.BK', 'NEO.BK', 'NEP.BK', 'NER.BK',
       'NETBAY.BK', 'NEW.BK', 'NEX.BK', 'NFC.BK', 'NKI.BK', 'NKT.BK', 'NL.BK',
       'NNCL.BK', 'NOBLE.BK', 'NOVA.BK', 'NPK.BK', 'NRF.BK'],
      dtype='object', name='Ticker')

In [25]:
#เฉพาะหุ้นตัวเดียว
data["LH.BK"].head()

Price           Open      High       Low     Close    Volume
Date
2025-04-03  3.931116  3.949747  3.893855  3.931116  40355800
2025-04-04  3.949747  3.968379  3.912486  3.968379  24598800
2025-04-08  3.875224  3.912486  3.782069  3.782069  45427500
2025-04-09  3.782069  3.893855  3.763439  3.893855  25768100
2025-04-10  3.931116  4.005640  3.912486  3.987010  28046100

In [24]:
data.head()

Ticker       LHFG.BK                                           MST.BK  \
Price           Open      High       Low     Close   Volume      Open
Date
2025-04-03  0.731263  0.740759  0.731263  0.731263  1188000  7.628918
2025-04-04  0.731263  0.731263  0.712269  0.731263  2943800  7.484977
2025-04-08  0.721766  0.721766  0.683778  0.702772  4401600  7.484976
2025-04-09  0.702772  0.721766  0.693275  0.702772  2658100  7.436996
2025-04-10  0.721766  0.721766  0.712269  0.712269  2557900  7.484977

Ticker                                            ...     MC.BK            \
Price           High       Low     Close  Volume  ...      Open      High
Date                                              ...
2025-04-03  7.676899  7.436996  7.676899   11600  ...  9.233157  9.233157
2025-04-04  7.532957  7.436996  7.532957    2400  ...  9.186991  9.186991
2025-04-08  7.484976  7.389015  7.436996   48900  ...  9.002329  9.002329
2025-04-09  7.436996  7.341035  7.389015   22700  ...  8.633003  8.679168
2025-04-10  7.484977  6.717286  6.909209  183600  ...  8.863831  9.002328

Ticker                                      MBK.BK                        \
Price            Low     Close   Volume       Open       High        Low
Date
2025-04-03  9.140825  9.233157  1504900  15.794204  15.888218  15.606179
2025-04-04  9.048494  9.048494  3003700  15.606179  15.606179  15.042100
2025-04-08  8.633003  8.679168  5036400  14.854075  15.042101  14.384009
2025-04-09  8.448339  8.586837  2071900  14.572035  14.760061  14.101969
2025-04-10  8.679167  8.725333  2438700  14.854074  15.136114  14.666048

Ticker
Price           Close   Volume
Date
2025-04-03  15.700192   771700
2025-04-04  15.042100  1214800
2025-04-08  14.478022  1532700
2025-04-09  14.478022  2237900
2025-04-10  14.666048  1167100

[5 rows x 500 columns]

In [26]:
#แปลงข้อมูลให้พร้อมใช้
all_data = []

for t in tickers_yf:
    try:
        df = data[t].copy()
        df["symbol"] = t.replace(".BK", "")
        df = df.reset_index()
        all_data.append(df)
    except:
        print(f"❌ ไม่มีข้อมูล: {t}")

final_df = pd.concat(all_data)
final_df.columns = [c.lower().replace(" ", "_") for c in final_df.columns]

final_df.head()

        date      open      high       low     close      volume symbol
0 2025-04-03  3.931116  3.949747  3.893855  3.931116  40355800.0     LH
1 2025-04-04  3.949747  3.968379  3.912486  3.968379  24598800.0     LH
2 2025-04-08  3.875224  3.912486  3.782069  3.782069  45427500.0     LH
3 2025-04-09  3.782069  3.893855  3.763439  3.893855  25768100.0     LH
4 2025-04-10  3.931116  4.005640  3.912486  3.987010  28046100.0     LH

In [27]:
#map เป็น stock_id
stocks_df = pd.read_sql("SELECT stock_id, symbol FROM stocks", engine)

stock_map = dict(zip(stocks_df["symbol"], stocks_df["stock_id"]))

final_df["stock_id"] = final_df["symbol"].map(stock_map)

In [28]:
#ปรับ column ให้ตรง DB
final_df.rename(columns={
    "date": "trade_date"
}, inplace=True)

final_df = final_df[
    ["trade_date", "open", "high", "low", "close", "volume", "stock_id"]
]

In [30]:
final_df.head()

  trade_date      open      high       low     close      volume  stock_id
0 2025-04-03  3.931116  3.949747  3.893855  3.931116  40355800.0       807
1 2025-04-04  3.949747  3.968379  3.912486  3.968379  24598800.0       807
2 2025-04-08  3.875224  3.912486  3.782069  3.782069  45427500.0       807
3 2025-04-09  3.782069  3.893855  3.763439  3.893855  25768100.0       807
4 2025-04-10  3.931116  4.005640  3.912486  3.987010  28046100.0       807

In [31]:
final_df.isnull().sum()

trade_date      0
open          938
high          938
low           938
close         938
volume        938
stock_id        0
dtype: int64

In [32]:
len(final_df)

24200

## insert ลง prices

In [33]:
final_df.to_sql(
    "prices",
    engine,
    if_exists="append",
    index=False
)

200

## ตรวจสอบใน DB

In [34]:
pd.read_sql("SELECT * FROM prices ORDER BY trade_date DESC LIMIT 10", engine)

,price_id,stock_id,trade_date,open,high,low,close,volume,market_cap
0,102774,812,2026-04-03,14.10,14.20,14.00,14.00,148100,None
1,103500,815,2026-04-03,3.68,3.68,3.66,3.68,27100,None
2,102048,809,2026-04-03,13.00,13.10,12.90,12.90,697300,None
3,102532,811,2026-04-03,4.30,4.34,4.30,4.34,139900,None
4,103016,813,2026-04-03,0.60,0.61,0.60,0.60,493300,None
5,103258,814,2026-04-03,1.34,1.36,1.34,1.35,171900,None
6,101564,807,2026-04-03,3.80,3.80,3.74,3.74,14005200,None
7,101806,808,2026-04-03,1.02,1.03,1.02,1.02,2579700,None
8,102290,810,2026-04-03,3.36,3.38,3.36,3.38,27800,None
9,103742,816,2026-04-03,1.59,1.59,1.57,1.58,186900,None

## ดึงชื่อบริษัทจริง 100% อัตโนมัติ”

In [36]:
symbols  = [
"LH","LHFG","LHHOTEL","LHK","LHRREIT","LHSC","LIT","LOXLEY","LPH","LPN",
"LRH","LST","LTMH","LTS","LUXF","M","MADAME","MAGURO","MAJOR","MALEE",
"MANRIN","MASTEC","MASTER","MATCH","MATI","MBAX","MBK","MC","MCA","M-CHAI",
"MCOT","MCS","MDX","MEB","MEDEZE","MEGA","MENA","META","METCO","MFC",
"MFEC","MGC","MGI","MGT","MICRO","MIDA","MII","MILL","MINT","MIPF",
"MITSIB","MJD","MJLF","MK","ML","MMM","MNIT","MNIT2","MNRF","MODERN",
"MONO","MOONG","MORE","MOSHI","MOTHER","M-PAT","MPJ","MRDIYT","MSC","MST",
"M-STOR","MTC","MTI","MTW","MUD","MVP","NAM","NAT","NATION","NC",
"NCAP","NCH","NCL","NCP","NDR","NEO","NEP","NER","NETBAY","NEW",
"NEX","NFC","NKI","NKT","NL","NNCL","NOBLE","NOVA","NPK","NRF"
]

In [37]:
!pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [38]:
import yfinance as yf
import pandas as pd

data = []

for sym in symbols:
    try:
        ticker = yf.Ticker(sym + ".BK")  # หุ้นไทยต้องเติม .BK
        info = ticker.info
        name = info.get("longName") or info.get("shortName") or sym
        
        data.append({
            "symbol": sym,
            "stock_name": name
        })
    except:
        data.append({
            "symbol": sym,
            "stock_name": sym
        })

df = pd.DataFrame(data)
df

     symbol                                         stock_name
0        LH             Land and Houses Public Company Limited
1      LHFG          LH Financial Group Public Company Limited
2   LHHOTEL    LH Hotel Leasehold Real Estate Investment Trust
3       LHK               Lohakit Metal Public Company Limited
4   LHRREIT  Land And Houses Residential Freehold And Lease...
..      ...                                                ...
95     NNCL                 Nava Nakorn Public Company Limited
96    NOBLE           Noble Development Public Company Limited
97     NOVA                 Nova Empire Public Company Limited
98      NPK           New Plus Knitting Public Company Limited
99      NRF          NR Instant Produce Public Company Limited

[100 rows x 2 columns]

In [39]:
df.head()

    symbol                                         stock_name
0       LH             Land and Houses Public Company Limited
1     LHFG          LH Financial Group Public Company Limited
2  LHHOTEL    LH Hotel Leasehold Real Estate Investment Trust
3      LHK               Lohakit Metal Public Company Limited
4  LHRREIT  Land And Houses Residential Freehold And Lease...

## เชื่อมต่อ postgres

In [40]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/thai_stock_market"
)

In [41]:
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in df.iterrows():
        conn.execute(text("""
            INSERT INTO stocks (symbol, stock_name)
            VALUES (:symbol, :stock_name)
            ON CONFLICT (symbol)
            DO UPDATE SET
                stock_name = EXCLUDED.stock_name
        """), {
            "symbol": row["symbol"],
            "stock_name": row["stock_name"]
        })

print("✅ Upsert completed (no duplicate error)")

✅ Upsert completed (no duplicate error)

In [42]:
pd.read_sql("SELECT * FROM stocks ORDER BY symbol", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20.0,None,None,None,None
1,2,3BBIF,3BB Internet Infrastructure Fund,20.0,None,None,None,None
2,3,88TH,88(Thailand) Public Company Limited,20.0,None,None,None,None
3,4,A,Areeya Property Public Company Limited,20.0,None,None,None,None
4,5,A5,Asset Five Group Public Company Limited,20.0,None,None,None,None
...,...,...,...,...,...,...,...,...
493,902,NNCL,Nava Nakorn Public Company Limited,NaN,None,None,None,None
494,903,NOBLE,Noble Development Public Company Limited,NaN,None,None,None,None
495,904,NOVA,Nova Empire Public Company Limited,NaN,None,None,None,None
496,905,NPK,New Plus Knitting Public Company Limited,NaN,None,None,None,None
497,906,NRF,NR Instant Produce Public Company Limited,NaN,None,None,None,None

# 📊 Stock Fundamental Data Pipeline (YFinance → PostgreSQL)

## 🎯 Objective
ดึงข้อมูลพื้นฐานของหุ้น (PE, PBV, EPS, Dividend Yield) จาก Yahoo Finance  
และบันทึกลง PostgreSQL

---

## ⚠️ Important Note
- ข้อมูล PE / PBV / EPS / Div Yield เป็น **ค่าปัจจุบัน (snapshot)**
- ❌ ไม่สามารถดึงย้อนหลังจาก yfinance ได้
- ✔ ต้องเก็บเองหากต้องการ historical

## (ใช้ DB เป็น source หลัก)
 ดึงหุ้นทั้งหมดจาก DB

In [6]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
import time

In [7]:
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="thai_stock_market",
    user="postgres",
    password="admin"
)

conn.autocommit = True
cur = conn.cursor()
print("Connected to thai_stock_market")

Connected to thai_stock_market

In [8]:
engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")
print ('เชื่อมต่อ')

เชื่อมต่อ

In [10]:
stocks_df = pd.read_sql("SELECT stock_id, symbol FROM stocks", engine)

print(len(stocks_df))  # ควรได้ ~900

932

## CELL: ดึง Fundamental ทั้งหมด

In [13]:
import yfinance as yf
import pandas as pd
import time

updates = []

for i, row in stocks_df.iterrows():
    symbol = row["symbol"]
    stock_id = row["stock_id"]

    try:
        ticker = yf.Ticker(symbol + ".BK")
        info = ticker.info

        updates.append({
            "stock_id": stock_id,
            "pe": info.get("trailingPE"),
            "pbv": info.get("priceToBook"),
            "eps": info.get("trailingEps"),
            "div_yield": info.get("dividendYield")
        })

        print(f"✅ {symbol}")

        # 🔥 กันโดน block
        if i % 50 == 0:
            time.sleep(2)

    except Exception as e:
        print(f"❌ {symbol}")

✅ 2S
✅ 3BBIF
✅ 88TH
✅ A
✅ A5
✅ AAI
✅ AAV
✅ ABM
✅ ACAP
✅ ACC
✅ ACE
✅ ACG
✅ ADB
✅ ADD
✅ ADVANC
✅ ADVICE
✅ AE
✅ AEONTS
✅ AF
✅ AFC
✅ AGE
✅ AH
✅ AHC
✅ AI
✅ AIE
✅ AIMCG
✅ AIMIRT
✅ AIRA
✅ AIT
✅ AJ
✅ AJA
✅ AKP
✅ AKR
✅ AKS
✅ ALLA
✅ ALLY
✅ ALPHAX
✅ ALT
✅ ALUCON
✅ AMA
✅ AMANAH
✅ AMARC
✅ AMARIN
✅ AMATA
✅ AMATAR
✅ AMATAV
✅ AMC
✅ AMR
✅ ANAN
✅ ANI
✅ AOT
✅ AP
✅ APCO
✅ APCS
✅ APO
✅ APP
✅ APURE
✅ AQUA
✅ ARIN
✅ ARIP
✅ ARROW
✅ AS
✅ ASAP
✅ ASEFA
✅ ASIA
✅ ASIAN
✅ ASIMAR
✅ ASK
✅ ASN
✅ ASP
✅ ASW
✅ ATLAS
✅ ATP30
✅ AU
✅ AUCT
✅ AURA
✅ AWC
✅ AXTRART
✅ AYUD
✅ B
✅ B52
✅ BA
✅ BAFS
✅ BAM
✅ BANPU
✅ MASTER
✅ MATCH
✅ MATI
✅ MBAX
✅ MBK
✅ MC
✅ MCA
✅ M-CHAI
✅ MCOT
✅ MCS
✅ MDX
✅ MEB
✅ MEDEZE
✅ MEGA
✅ MENA
✅ META
✅ METCO
✅ MFC
✅ MFEC
✅ MGC
✅ MGI
✅ MGT
✅ MICRO
✅ MIDA
✅ MII
✅ MILL
✅ MINT
✅ MIPF
✅ MITSIB
✅ MJD
✅ MJLF
✅ MK
✅ ML
✅ MMM
✅ MNIT
✅ MNIT2
✅ MNRF
✅ MODERN
✅ MONO
✅ MOONG
✅ MORE
✅ MOSHI
✅ MOTHER
✅ M-PAT
✅ MPJ
✅ MRDIYT
✅ MSC
✅ MST
✅ CRD
✅ CREDIT
✅ CSC
✅ CSP
✅ CSR
✅ CSS
✅ CTARAF
✅ CTW
✅ CV
✅ CWT
✅ D
✅ DCC
✅ DCON
✅ LH
✅ LHFG
✅ LHHOTEL
✅ BAREIT
✅ BAY
✅ BBGI
✅ BBIK
✅ BBL
✅ BC
✅ BCH
✅ BCP
✅ BCPG
✅ BCT
✅ BDMS
✅ BE8
✅ BEAUTY
✅ BEC
✅ BEM
✅ BEYOND
✅ BGC
✅ BGRIM
✅ BGT
✅ BH
✅ BIG
✅ BIOTEC
✅ BIS
✅ BIZ
✅ BJC
✅ BJCHI
✅ BKA
✅ BKD
✅ BKGI
✅ BKIH
✅ BLA
✅ BLAND
✅ BLC
✅ BLESS
✅ BLISS
✅ BM
✅ BOFFICE
✅ BOL
✅ BPP
✅ BPS
✅ BR
✅ BRI
✅ BROCK
✅ BRR
✅ BRRGIF
✅ BSBM
✅ BSM
✅ BTC
✅ BTG
✅ BTNC
✅ BTS
✅ BTSGIF
✅ BTW
✅ BUI
✅ BVG
✅ BWG
✅ B-WORK
✅ BYD
✅ CAZ
✅ CBG
✅ CCET
✅ CCP
✅ CEN
✅ CENTEL
✅ CEYE
✅ CFARM
✅ CFRESH
✅ CGD
✅ CGH
✅ CH
✅ CHAO
✅ CHARAN
✅ CHASE
✅ CHAYO
✅ CHEWA
✅ CHG
✅ CHIC
✅ CHO
✅ CHOTI
✅ CHOW
✅ CI
✅ CIG
✅ CIMBT
✅ CITY
✅ CIVIL
✅ CK
✅ CKP
✅ CM
✅ CMAN
✅ CMC
✅ CMO
✅ CMR
✅ CNT
✅ COCOCO
✅ COLOR
✅ COM7
✅ COMAN
✅ CPALL
✅ CPANEL
✅ CPAXT
✅ CPF
✅ CPH
✅ CPI
✅ CPL
✅ CPN
✅ CPNCG
✅ CPNREIT
✅ CPR
✅ CPT
✅ CPTREIT
✅ CPW
✅ CRANE
✅ CRC
✅ DDD
✅ DELTA
✅ DEMCO
✅ DEXON
✅ DHOUSE
✅ DIF
✅ DIMET
✅ DITTO
✅ DMT
✅ DOD
✅ DOHOME
✅ DPAINT
✅ DREIT
✅ DRT
✅ DTCENT
✅ DTCI
✅ DUSIT
✅ DV8
✅ EA
✅ EASON
✅ EAST
✅ EASTW
✅ ECF
✅ EFORL
✅ EGATIF
✅ EGCO
✅ EKH
✅ EMC
✅ EMPIRE
✅ EP
✅ EPG
✅ ERW
✅ ESTAR
✅ ETC
✅ ETE
✅ ETL
✅ EURO
✅ EVER
✅ F&D
✅ FANCY
✅ FE
✅ FLOYD
✅ FM
✅ FMT
✅ FN
✅ FNS
✅ FORTH
✅ FPI
✅ FPT
✅ FSMART
✅ FSX
✅ FTE
✅ FTI
✅ FTREIT
✅ FUTURERT
✅ FVC
✅ GABLE
✅ GAHREIT
✅ GBX
✅ GC
✅ GCAP
✅ GEL
✅ GENCO
✅ GFC
✅ GFPT
✅ GGC
✅ GJS
✅ GLAND
✅ GLOBAL
✅ GLORY
✅ GPI
✅ GPSC
✅ GRAMMY
✅ GRAND
✅ GREEN
✅ GROREIT
✅ GSTEEL
✅ GTB
✅ GTV
✅ GULF
✅ GUNKUL
✅ GVREIT
✅ GYT
✅ HANA
✅ HANN
✅ HARN
✅ HEALTH
✅ HENG
✅ HFT
✅ HL
✅ HMPRO
✅ HPF
✅ HPT
✅ HTC
✅ HTECH
✅ HUMAN
✅ HYDRO
✅ HYDROGEN
✅ I2
✅ ICC
✅ ICHI
✅ ICN
✅ IDG
✅ IFS
✅ IHL
✅ IIG
✅ III
✅ ILINK
✅ ILM
✅ IMH
✅ IMPACT
✅ IND
✅ INET
✅ INETREIT
✅ INGRS
✅ INOX
✅ INSET
✅ INSURE
✅ IP
✅ IRC
✅ IRCP
✅ IROYAL
✅ IRPC
✅ ISSARA
✅ IT
✅ ITC
✅ ITD
✅ ITEL
✅ ITNS
✅ ITTHI
✅ IVF
✅ IVL
✅ J
✅ JAK
✅ JAS
✅ JCK
✅ JCT
✅ JDF
✅ JMART
✅ JMT
✅ JPARK
✅ JR
✅ JSP
✅ JTS
✅ JUBILE
✅ K
✅ KAMART
✅ KASET
✅ KBANK
✅ KBS
✅ KBSPIF
✅ KC
✅ KCAR
✅ KCC
✅ KCE
✅ KCG
✅ KCM
✅ KDH
✅ KGEN
✅ KGI
✅ KIAT
✅ KISS
✅ KJL
✅ KK
✅ KKC
✅ KKP
✅ KLINIQ
✅ KOOL
✅ KPNREIT
✅ KSL
✅ KTB
✅ KTBSTMR
✅ KTC
✅ KTIS
✅ KTMS
✅ KUMWEL
✅ KUN
✅ KWC
✅ KWI
✅ KWM
✅ KYE
✅ L&E
✅ LALIN
✅ LANNA
✅ LDC
✅ LEE
✅ LEO
✅ LHK
✅ LHRREIT
✅ LHSC
✅ LIT
✅ LOXLEY
✅ LPH
✅ LPN
✅ LRH
✅ LST
✅ LTMH
✅ LTS
✅ LUXF
✅ M
✅ MADAME
✅ MAGURO
✅ MAJOR
✅ MALEE
✅ MANRIN
✅ MASTEC
✅ M-STOR
✅ MTC
✅ MTI
✅ MTW
✅ MUD
✅ MVP
✅ NAM
✅ NAT
✅ NATION
✅ NC
✅ NCAP
✅ NCH
✅ NCL
✅ NCP
✅ NDR
✅ NEO
✅ NEP
✅ NER
✅ NETBAY
✅ NEW
✅ NEX
✅ NFC
✅ NKI
✅ NKT
✅ NL
✅ NNCL
✅ NOBLE
✅ NOVA
✅ NPK
✅ NRF
✅ NSL
✅ NTF
✅ NTSC
✅ NTV
✅ NUT
✅ NV
✅ NVD
✅ NWR
✅ NYT
✅ OCC
✅ OGC
✅ OHTL
✅ OKJ
✅ ONEE
✅ ONSENS
✅ OR
✅ ORI
✅ ORN
✅ OSP
✅ PACO
✅ PAF
✅ PANEL
✅ PAP
✅ PATO
✅ PB
✅ PCC
✅ PCE
✅ PCSGH
✅ PDG
✅ PDJ
✅ PEACE
✅ PEER
✅ PERM
✅ PF
✅ PG
✅ PHG
✅ PHOL
✅ PICO
✅ PIMO
✅ PIN
✅ PIS
✅ PJW
✅ PK
✅ PL
✅ PLANB
✅ PLANET
✅ PLAT
✅ PLE
✅ PLT
✅ PLUS
✅ PM
✅ PMC
✅ PMTA
✅ POLY
✅ POPF
✅ PORT
✅ PPM
✅ PPP
✅ PPPM
✅ PPS
✅ PQS
✅ PR9
✅ PRAKIT
✅ PRAPAT
✅ PREB
✅ PRECHA
✅ PRG
✅ PRI
✅ PRIME
✅ PRIN
✅ PRINC
✅ PRM
✅ PROEN
✅ PROS
✅ PROSPECT
✅ PROUD
✅ PRTR
✅ PSGC
✅ PSH
✅ PSL
✅ PSP
✅ PSTC
✅ PT
✅ PTC
✅ PTECH
✅ PTG
✅ PTL
✅ PTT
✅ PTTEP
✅ PTTGC
✅ PYLON
✅ Q-CON
✅ QDC
✅ QH
✅ QHBREIT
✅ QHHRREIT
✅ QHOP
✅ QLT
✅ QTC
✅ QTCG
✅ RABBIT
✅ RAM
✅ RATCH
✅ RBF
✅ RCL
✅ READY
✅ RICHY
✅ RJH
✅ RML
✅ ROCK
✅ ROCTEC
✅ ROH
✅ ROJNA
✅ RP
✅ RPC
✅ RPH
✅ RS
✅ RSP
✅ RT
✅ RWI
✅ S
✅ S&J
✅ S11
✅ SA
✅ SAAM
✅ SABINA
✅ SAF
✅ SAFE
✅ SAK
✅ SALEE
✅ SAM
✅ SAMART
✅ SAMCO
✅ SAMTEL
✅ SANKO
✅ SAPPE
✅ SAT
✅ SAUCE
✅ SAV
✅ SAWAD
✅ SAWANG
✅ SC
✅ SCAP
✅ SCB
✅ SCC
✅ SCCC
✅ SCG
✅ SCGD
✅ SCGP
✅ SCI
✅ SCL
✅ SCM
✅ SCN
✅ SCP
✅ SDC
✅ SE
✅ SEAFCO
✅ SEAOIL
✅ SECURE
✅ SE-ED
✅ SEI
✅ SELIC
✅ SENA
✅ SENX
✅ SFLEX
✅ SFT
✅ SGC
✅ SGF
✅ SGP
✅ SHANG
✅ SHR
✅ SIAM
✅ SICT
✅ SIMAT
✅ SINGER
✅ SINO
✅ SIRI
✅ SIRIPRT
✅ SIS
✅ SISB
✅ SITHAI
✅ SJWD
✅ SK
✅ SKE
✅ SKIN
✅ SKN
✅ SKR
✅ SKY
✅ SLP
✅ SMART
✅ SMD100
✅ SMIT
✅ SMO
✅ SMPC
✅ SMT
✅ SNC
✅ SNNP
✅ SNP
✅ SNPS
✅ SO
✅ SOLAR
✅ SONIC
✅ SORKON
✅ SPA
✅ SPACK
✅ SPALI
✅ SPC
✅ SPCG
✅ SPG
✅ SPI
✅ SPRC
✅ SPREME
✅ SPRIME
✅ SPTX
✅ SPVI
✅ SQ
✅ SR
✅ SRICHA
✅ SRIPANWA
✅ SRS
✅ SSF
✅ SSP
✅ SSPF
✅ SSSC
✅ SST
✅ SSTRT
✅ STA
✅ STANLY
✅ STARM
✅ STC
✅ STECH
✅ STECON
✅ STELLA
✅ STGT
✅ STI
✅ STOWER
✅ STP
✅ STPI
✅ STX
✅ SUC
✅ SUN
✅ SUPER
✅ SUPEREIF
✅ SUSCO
✅ SUTHA
✅ SVI
✅ SVOA
✅ SVR
✅ SVT
✅ SWC
✅ SYMC
✅ SYNEX
✅ SYNTEC
✅ TACC
✅ TAE
✅ TAKUNI
✅ TAN
✅ TAPAC
✅ TASCO
✅ TATG
✅ TBN
✅ TC
✅ TCAP
✅ TCC
✅ TCJ
✅ TCMC
✅ TCOAT
✅ TEAM
✅ TEAMG
✅ TEGH
✅ TEKA
✅ TERA
✅ TFFIF
✅ TFG
✅ TFI
✅ TFM
✅ TFMAMA
✅ TGE
✅ TGH
✅ TGPRO
✅ TH
✅ THAI
✅ THANA
✅ THANI
✅ THCOM
✅ THE
✅ THG
✅ THIP
✅ THMUI
✅ THRE
✅ THREL
✅ TIDLOR
✅ TIF1
✅ TIGER
✅ TIPCO
✅ TIPH
✅ TISCO
✅ TITLE
✅ TK
✅ TKC
✅ TKN
✅ TKS
✅ TKT
✅ TL
✅ TLHPF
✅ TLI
✅ TM
✅ TMAN
✅ TMC
✅ TMD
✅ TMI
✅ TMILL
✅ TMT
✅ TMW
✅ TNDT
✅ TNH
✅ TNITY
✅ TNL
✅ TNP
✅ TNPC
✅ TNPF
✅ TNR
✅ TOA
✅ TOG
✅ TOP
✅ TOPP
✅ TPA
✅ TPAC
✅ TPBI
✅ TPCH
✅ TPCS
✅ TPIPL
✅ TPIPP
✅ TPL
✅ TPLAS
✅ TPOLY
✅ TPP
✅ TPRIME
✅ TPS
✅ TQM
✅ TQR
✅ TR
✅ TRC
✅ TRITN
✅ TRP
✅ TRT
✅ TRU
✅ TRUBB
✅ TRUE
✅ TRV
✅ TSC
✅ TSE
✅ TSI
✅ TSR
✅ TSTE
✅ TSTH
✅ TTA
✅ TTB
✅ TTCL
✅ TTI
✅ TTLPF
✅ TTT
✅ TTW
✅ TU
✅ TU-PF
✅ TURBO
✅ TURTLE
✅ TVDH
✅ TVH
✅ TVO
✅ TVT
✅ TWP
✅ TWPC
✅ TWZ
✅ TYCN
✅ UAC
✅ UBA
✅ UBE
✅ UBIS
✅ UEC
✅ UKEM
✅ UMI
✅ UMS
✅ UNIQ
✅ UOBKH
✅ UP
✅ UPF
✅ UPOIC
✅ UREKA
✅ UTP
✅ UV
✅ UVAN
✅ VARO
✅ VCOM
✅ VGI
✅ VIBHA
✅ VIH
✅ VL
✅ VNG
✅ VPO
✅ VRANDA
✅ VS
✅ WACOAL
✅ WARRIX
✅ WASH
✅ WAVE

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WELL.BK"}}}

✅ WELL
✅ WFX
✅ WGE
✅ WHA
✅ WHABT
✅ WHAIR
✅ WHART
✅ WHAUP
✅ WICE
✅ WIIK
✅ WIN
✅ WINDOW
✅ WINMED
✅ WINNER
✅ WORK
✅ WP
✅ WPH
✅ WSOL
✅ XBIO
✅ XO
✅ XPG
✅ XYZ
✅ YGG
✅ YONG
✅ YUASA
✅ ZAA
✅ ZEN
✅ ZIGA

## แปลงเป็น DataFrame

In [14]:
df_update = pd.DataFrame(updates)

print(len(df_update))
df_update.head()

932

   stock_id         pe       pbv   eps  div_yield
0         1  10.538462  0.738744  0.26       8.63
1         2       None       NaN   NaN        NaN
2         3   8.642858  2.113537  0.56       3.73
3         4       None  3.190508 -0.99        NaN
4         5  20.555555  1.295518  0.09       2.72

## UPDATE ลง PostgreSQL

In [25]:
import numpy as np

# แปลงเป็น numeric + กัน error
df_update["pe"] = pd.to_numeric(df_update["pe"], errors="coerce")
df_update["pbv"] = pd.to_numeric(df_update["pbv"], errors="coerce")
df_update["eps"] = pd.to_numeric(df_update["eps"], errors="coerce")
df_update["div_yield"] = pd.to_numeric(df_update["div_yield"], errors="coerce")

# 🔥 แปลง Infinity → NaN
df_update.replace([np.inf, -np.inf], np.nan, inplace=True)

In [26]:
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in df_update.iterrows():
        conn.execute(text("""
            UPDATE stocks
            SET 
                pe = :pe,
                pbv = :pbv,
                eps = :eps,
                div_yield = :div_yield
            WHERE stock_id = :stock_id
        """), row.to_dict())

In [27]:
df_update[df_update["pe"] == float("inf")]

Empty DataFrame
Columns: [stock_id, pe, pbv, eps, div_yield]
Index: []

In [28]:
df_update = df_update.where(pd.notnull(df_update), None)

In [21]:
df_update = pd.DataFrame(updates)

print(len(df_update))
df_update.head()

932

   stock_id         pe       pbv   eps  div_yield
0         1  10.538462  0.738744  0.26       8.63
1         2       None       NaN   NaN        NaN
2         3   8.642858  2.113537  0.56       3.73
3         4       None  3.190508 -0.99        NaN
4         5  20.555555  1.295518  0.09       2.72

In [23]:
import numpy as np

# แปลงเป็น numeric + กัน error
df_update["pe"] = pd.to_numeric(df_update["pe"], errors="coerce")
df_update["pbv"] = pd.to_numeric(df_update["pbv"], errors="coerce")
df_update["eps"] = pd.to_numeric(df_update["eps"], errors="coerce")
df_update["div_yield"] = pd.to_numeric(df_update["div_yield"], errors="coerce")

# 🔥 แปลง Infinity → NaN
df_update.replace([np.inf, -np.inf], np.nan, inplace=True)

In [24]:
df_update = df_update.where(pd.notnull(df_update), None)

In [31]:
pd.read_sql("""
SELECT symbol, pe, pbv, eps, div_yield
FROM stocks
WHERE pe IS NOT NULL
LIMIT 20
""", engine)

    symbol     pe     pbv   eps  div_yield
0    BGRIM  39.66    1.71  0.29       3.49
1      BGT    NaN    0.42 -0.03        NaN
2       BH  19.34    4.31  8.66       2.97
3      BIG   9.67    0.56  0.03       3.45
4   BIOTEC  27.00    0.76  0.01        NaN
5      BIS  16.67    0.80  0.12       3.96
6      BIZ   9.18    2.89  0.51      10.73
7      BJC  14.70    0.49  1.00       3.42
8       2S  10.54    0.74  0.26       8.63
9    3BBIF    NaN     NaN   NaN        NaN
10    88TH   8.64    2.11  0.56       3.73
11       A    NaN    3.19 -0.99        NaN
12      A5  20.56    1.30  0.09       2.72
13     AAI   9.83    1.51  0.35       7.57
14     AAV   6.11    1.04  0.18        NaN
15     ABM    NaN    0.49 -0.15        NaN
16    MNRF  42.98    0.27  0.05        NaN
17  MODERN  15.00    0.67  0.14       7.08
18    MONO    NaN  242.50 -0.12        NaN
19   MOONG  12.44    0.72  0.18      10.18

## 👉 แปลง Infinity NaN  → NULL
 ปัญหาตอนนี้
insert ข้อมูลที่ยังไม่ clean ลง PostgreSQL แล้ว
ทำให้มีค่า:
❌ Infinity
❌ ค่าเพี้ยน / overflow
❌ หรือค่าที่ไม่ควรอยู่

insert ข้อมูลที่ยังไม่ clean ลง PostgreSQL

## (Reset → Clean → Update ใหม่)

## Connect Database

In [90]:
from sqlalchemy import create_engine, text
import pandas as pd
import numpy as np

engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")

## ตรวจ df_update ก่อน

In [91]:
df_update.head()

   stock_id         pe       pbv   eps  div_yield
0         1  10.538462  0.738744  0.26       8.63
1         2        NaN       NaN   NaN        NaN
2         3   8.642858  2.113537  0.56       3.73
3         4        NaN  3.190508 -0.99        NaN
4         5  20.555555  1.295518  0.09       2.72

## Clean Data ก่อน update

In [92]:
import numpy as np

df_update = df_update.copy()

# แปลงเป็นตัวเลข
for col in ["pe","pbv","eps","div_yield"]:
    df_update[col] = pd.to_numeric(df_update[col], errors="coerce")

# แปลง infinity → NaN
df_update.replace([np.inf, -np.inf], np.nan, inplace=True)

# แปลง NaN → None
df_update = df_update.where(pd.notnull(df_update), None)

print("✅ clean แล้ว")

✅ clean แล้ว

In [93]:
# 1. upload dataframe เป็น temp table
df_update.to_sql("temp_fund", engine, if_exists="replace", index=False)

932

In [94]:
# 2. update join
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        UPDATE stocks s
        SET 
            pe = t.pe,
            pbv = t.pbv,
            eps = t.eps,
            div_yield = t.div_yield
        FROM temp_fund t
        WHERE s.stock_id = t.stock_id
    """))

print("✅ UPDATE สำเร็จ (finish)")

✅ UPDATE สำเร็จ (finish)

In [86]:
pd.read_sql("""
SELECT 
    stock_id,
    symbol,
    pe,
    pbv,
    eps,
    div_yield
FROM stocks
ORDER BY stock_id
LIMIT 20
""", engine)

    stock_id  symbol     pe    pbv    eps  div_yield
0          1      2S  10.54   0.74   0.26       8.63
1          2   3BBIF    NaN    NaN    NaN        NaN
2          3    88TH   8.64   2.11   0.56       3.73
3          4       A    NaN   3.19  -0.99        NaN
4          5      A5  20.56   1.30   0.09       2.72
5          6     AAI   9.83   1.51   0.35       7.57
6          7     AAV   6.11   1.04   0.18        NaN
7          8     ABM    NaN   0.49  -0.15        NaN
8          9    ACAP    NaN   0.15    NaN        NaN
9         10     ACC    NaN   1.36  -0.04        NaN
10        11     ACE  16.00   0.76   0.08       0.78
11        12     ACG  13.20   0.54   0.05       6.06
12        13     ADB  14.75   0.66   0.04       5.17
13        14     ADD  13.76   1.13   0.25      10.53
14        15  ADVANC  22.68  10.13  16.09       4.62
15        16  ADVICE  12.56   3.37   0.43       6.42
16        17      AE    NaN   0.20  -0.03        NaN
17        18  AEONTS   7.72   0.84  11.66       6.04
18        19      AF  35.00   1.05   0.01        NaN
19        20     AFC  10.28   0.12   0.29        NaN

## UPDATE ลง PostgreSQL

## 🎯 สรุป Flow ที่ทำ
 reset ค่าเก่า ❌
 clean data ✔
 update ใหม่ ✔
 ตรวจสอบ ✔

## 📊 ดึง Market Cap หุ้นไทย + บันทึกลง PostgreSQL

In [9]:
!pip install yfinance pandas sqlalchemy psycopg2-binary tqdm

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (4.67.1)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

## แปลงรายชื่อทั้งหมด → Python List

In [27]:
raw = """"2S"
"3BBIF"
"88TH"
"A"
"A5"
"AAI"
"AAV"
"ABM"
"ACAP"
"ACC"
"ACE"
"ACG"
"ADB"
"ADD"
"ADVANC"
"ADVICE"
"AE"
"AEONTS"
"AF"
"AFC"
"AGE"
"AH"
"AHC"
"AI"
"AIE"
"AIMCG"
"AIMIRT"
"AIRA"
"AIT"
"AJ"
"AJA"
"AKP"
"AKR"
"AKS"
"ALLA"
"ALLY"
"ALPHAX"
"ALT"
"ALUCON"
"AMA"
"AMANAH"
"AMARC"
"AMARIN"
"AMATA"
"AMATAR"
"AMATAV"
"AMC"
"AMR"
"ANAN"
"ANI"
"AOT"
"AP"
"APCO"
"APCS"
"APO"
"APP"
"APURE"
"AQUA"
"ARIN"
"ARIP"
"ARROW"
"AS"
"ASAP"
"ASEFA"
"ASIA"
"ASIAN"
"ASIMAR"
"ASK"
"ASN"
"ASP"
"ASW"
"ATLAS"
"ATP30"
"AU"
"AUCT"
"AURA"
"AWC"
"AXTRART"
"AYUD"
"B"
"B52"
"BA"
"BAFS"
"BAM"
"BANPU"
"BAREIT"
"BAY"
"BBGI"
"BBIK"
"BBL"
"BC"
"BCH"
"BCP"
"BCPG"
"BCT"
"BDMS"
"BE8"
"BEAUTY"
"BEC"
"BEM"
"BEYOND"
"BGC"
"BGRIM"
"BGT"
"BH"
"BIG"
"BIOTEC"
"BIS"
"BIZ"
"BJC"
"BJCHI"
"BKA"
"BKD"
"BKGI"
"BKIH"
"BLA"
"BLAND"
"BLC"
"BLESS"
"BLISS"
"BM"
"BOFFICE"
"BOL"
"BPP"
"BPS"
"BR"
"BRI"
"BROCK"
"BRR"
"BRRGIF"
"BSBM"
"BSM"
"BTC"
"BTG"
"BTNC"
"BTS"
"BTSGIF"
"BTW"
"BUI"
"BVG"
"BWG"
"B-WORK"
"BYD"
"CAZ"
"CBG"
"CCET"
"CCP"
"CEN"
"CENTEL"
"CEYE"
"CFARM"
"CFRESH"
"CGD"
"CGH"
"CH"
"CHAO"
"CHARAN"
"CHASE"
"CHAYO"
"CHEWA"
"CHG"
"CHIC"
"CHO"
"CHOTI"
"CHOW"
"CI"
"CIG"
"CIMBT"
"CITY"
"CIVIL"
"CK"
"CKP"
"CM"
"CMAN"
"CMC"
"CMO"
"CMR"
"CNT"
"COCOCO"
"COLOR"
"COM7"
"COMAN"
"CPALL"
"CPANEL"
"CPAXT"
"CPF"
"CPH"
"CPI"
"CPL"
"CPN"
"CPNCG"
"CPNREIT"
"CPR"
"CPT"
"CPTREIT"
"CPW"
"CRANE"
"CRC"
"CRD"
"CREDIT"
"CSC"
"CSP"
"CSR"
"CSS"
"CTARAF"
"CTW"
"CV"
"CWT"
"D"
"DCC"
"DCON"
"DDD"
"DELTA"
"DEMCO"
"DEXON"
"DHOUSE"
"DIF"
"DIMET"
"DITTO"
"DMT"
"DOD"
"DOHOME"
"DPAINT"
"DREIT"
"DRT"
"DTCENT"
"DTCI"
"DUSIT"
"DV8"
"EA"
"EASON"
"EAST"
"EASTW"
"ECF"
"EFORL"
"EGATIF"
"EGCO"
"EKH"
"EMC"
"EMPIRE"
"EP"
"EPG"
"ERW"
"ESTAR"
"ETC"
"ETE"
"ETL"
"EURO"
"EVER"
"F&D"
"FANCY"
"FE"
"FLOYD"
"FM"
"FMT"
"FN"
"FNS"
"FORTH"
"FPI"
"FPT"
"FSMART"
"FSX"
"FTE"
"FTI"
"FTREIT"
"FUTURERT"
"FVC"
"GABLE"
"GAHREIT"
"GBX"
"GC"
"GCAP"
"GEL"
"GENCO"
"GFC"
"GFPT"
"GGC"
"GJS"
"GLAND"
"GLOBAL"
"GLORY"
"GPI"
"GPSC"
"GRAMMY"
"GRAND"
"GREEN"
"GROREIT"
"GSTEEL"
"GTB"
"GTV"
"GULF"
"GUNKUL"
"GVREIT"
"GYT"
"HANA"
"HANN"
"HARN"
"HEALTH"
"HENG"
"HFT"
"HL"
"HMPRO"
"HPF"
"HPT"
"HTC"
"HTECH"
"HUMAN"
"HYDRO"
"HYDROGEN"
"I2"
"ICC"
"ICHI"
"ICN"
"IDG"
"IFS"
"IHL"
"IIG"
"III"
"ILINK"
"ILM"
"IMH"
"IMPACT"
"IND"
"INET"
"INETREIT"
"INGRS"
"INOX"
"INSET"
"INSURE"
"IP"
"IRC"
"IRCP"
"IROYAL"
"IRPC"
"ISSARA"
"IT"
"ITC"
"ITD"
"ITEL"
"ITNS"
"ITTHI"
"IVF"
"IVL"
"J"
"JAK"
"JAS"
"JCK"
"JCT"
"JDF"
"JMART"
"JMT"
"JPARK"
"JR"
"JSP"
"JTS"
"JUBILE"
"K"
"KAMART"
"KASET"
"KBANK"
"KBS"
"KBSPIF"
"KC"
"KCAR"
"KCC"
"KCE"
"KCG"
"KCM"
"KDH"
"KGEN"
"KGI"
"KIAT"
"KISS"
"KJL"
"KK"
"KKC"
"KKP"
"KLINIQ"
"KOOL"
"KPNREIT"
"KSL"
"KTB"
"KTBSTMR"
"KTC"
"KTIS"
"KTMS"
"KUMWEL"
"KUN"
"KWC"
"KWI"
"KWM"
"KYE"
"L&E"
"LALIN"
"LANNA"
"LDC"
"LEE"
"LEO"
"LH"
"LHFG"
"LHHOTEL"
"LHK"
"LHRREIT"
"LHSC"
"LIT"
"LOXLEY"
"LPH"
"LPN"
"LRH"
"LST"
"LTMH"
"LTS"
"LUXF"
"M"
"MADAME"
"MAGURO"
"MAJOR"
"MALEE"
"MANRIN"
"MASTEC"
"MASTER"
"MATCH"
"MATI"
"MBAX"
"MBK"
"MC"
"MCA"
"M-CHAI"
"MCOT"
"MCS"
"MDX"
"MEB"
"MEDEZE"
"MEGA"
"MENA"
"META"
"METCO"
"MFC"
"MFEC"
"MGC"
"MGI"
"MGT"
"MICRO"
"MIDA"
"MII"
"MILL"
"MINT"
"MIPF"
"MITSIB"
"MJD"
"MJLF"
"MK"
"ML"
"MMM"
"MNIT"
"MNIT2"
"MNRF"
"MODERN"
"MONO"
"MOONG"
"MORE"
"MOSHI"
"MOTHER"
"M-PAT"
"MPJ"
"MRDIYT"
"MSC"
"MST"
"M-STOR"
"MTC"
"MTI"
"MTW"
"MUD"
"MVP"
"NAM"
"NAT"
"NATION"
"NC"
"NCAP"
"NCH"
"NCL"
"NCP"
"NDR"
"NEO"
"NEP"
"NER"
"NETBAY"
"NEW"
"NEX"
"NFC"
"NKI"
"NKT"
"NL"
"NNCL"
"NOBLE"
"NOVA"
"NPK"
"NRF"
"NSL"
"NTF"
"NTSC"
"NTV"
"NUT"
"NV"
"NVD"
"NWR"
"NYT"
"OCC"
"OGC"
"OHTL"
"OKJ"
"ONEE"
"ONSENS"
"OR"
"ORI"
"ORN"
"OSP"
"PACO"
"PAF"
"PANEL"
"PAP"
"PATO"
"PB"
"PCC"
"PCE"
"PCSGH"
"PDG"
"PDJ"
"PEACE"
"PEER"
"PERM"
"PF"
"PG"
"PHG"
"PHOL"
"PICO"
"PIMO"
"PIN"
"PIS"
"PJW"
"PK"
"PL"
"PLANB"
"PLANET"
"PLAT"
"PLE"
"PLT"
"PLUS"
"PM"
"PMC"
"PMTA"
"POLY"
"POPF"
"PORT"
"PPM"
"PPP"
"PPPM"
"PPS"
"PQS"
"PR9"
"PRAKIT"
"PRAPAT"
"PREB"
"PRECHA"
"PRG"
"PRI"
"PRIME"
"PRIN"
"PRINC"
"PRM"
"PROEN"
"PROS"
"PROSPECT"
"PROUD"
"PRTR"
"PSGC"
"PSH"
"PSL"
"PSP"
"PSTC"
"PT"
"PTC"
"PTECH"
"PTG"
"PTL"
"PTT"
"PTTEP"
"PTTGC"
"PYLON"
"Q-CON"
"QDC"
"QH"
"QHBREIT"
"QHHRREIT"
"QHOP"
"QLT"
"QTC"
"QTCG"
"RABBIT"
"RAM"
"RATCH"
"RBF"
"RCL"
"READY"
"RICHY"
"RJH"
"RML"
"ROCK"
"ROCTEC"
"ROH"
"ROJNA"
"RP"
"RPC"
"RPH"
"RS"
"RSP"
"RT"
"RWI"
"S"
"S&J"
"S11"
"SA"
"SAAM"
"SABINA"
"SAF"
"SAFE"
"SAK"
"SALEE"
"SAM"
"SAMART"
"SAMCO"
"SAMTEL"
"SANKO"
"SAPPE"
"SAT"
"SAUCE"
"SAV"
"SAWAD"
"SAWANG"
"SC"
"SCAP"
"SCB"
"SCC"
"SCCC"
"SCG"
"SCGD"
"SCGP"
"SCI"
"SCL"
"SCM"
"SCN"
"SCP"
"SDC"
"SE"
"SEAFCO"
"SEAOIL"
"SECURE"
"SE-ED"
"SEI"
"SELIC"
"SENA"
"SENX"
"SFLEX"
"SFT"
"SGC"
"SGF"
"SGP"
"SHANG"
"SHR"
"SIAM"
"SICT"
"SIMAT"
"SINGER"
"SINO"
"SIRI"
"SIRIPRT"
"SIS"
"SISB"
"SITHAI"
"SJWD"
"SK"
"SKE"
"SKIN"
"SKN"
"SKR"
"SKY"
"SLP"
"SMART"
"SMD100"
"SMIT"
"SMO"
"SMPC"
"SMT"
"SNC"
"SNNP"
"SNP"
"SNPS"
"SO"
"SOLAR"
"SONIC"
"SORKON"
"SPA"
"SPACK"
"SPALI"
"SPC"
"SPCG"
"SPG"
"SPI"
"SPRC"
"SPREME"
"SPRIME"
"SPTX"
"SPVI"
"SQ"
"SR"
"SRICHA"
"SRIPANWA"
"SRS"
"SSF"
"SSP"
"SSPF"
"SSSC"
"SST"
"SSTRT"
"STA"
"STANLY"
"STARM"
"STC"
"STECH"
"STECON"
"STELLA"
"STGT"
"STI"
"STOWER"
"STP"
"STPI"
"STX"
"SUC"
"SUN"
"SUPER"
"SUPEREIF"
"SUSCO"
"SUTHA"
"SVI"
"SVOA"
"SVR"
"SVT"
"SWC"
"SYMC"
"SYNEX"
"SYNTEC"
"TACC"
"TAE"
"TAKUNI"
"TAN"
"TAPAC"
"TASCO"
"TATG"
"TBN"
"TC"
"TCAP"
"TCC"
"TCJ"
"TCMC"
"TCOAT"
"TEAM"
"TEAMG"
"TEGH"
"TEKA"
"TERA"
"TFFIF"
"TFG"
"TFI"
"TFM"
"TFMAMA"
"TGE"
"TGH"
"TGPRO"
"TH"
"THAI"
"THANA"
"THANI"
"THCOM"
"THE"
"THG"
"THIP"
"THMUI"
"THRE"
"THREL"
"TIDLOR"
"TIF1"
"TIGER"
"TIPCO"
"TIPH"
"TISCO"
"TITLE"
"TK"
"TKC"
"TKN"
"TKS"
"TKT"
"TL"
"TLHPF"
"TLI"
"TM"
"TMAN"
"TMC"
"TMD"
"TMI"
"TMILL"
"TMT"
"TMW"
"TNDT"
"TNH"
"TNITY"
"TNL"
"TNP"
"TNPC"
"TNPF"
"TNR"
"TOA"
"TOG"
"TOP"
"TOPP"
"TPA"
"TPAC"
"TPBI"
"TPCH"
"TPCS"
"TPIPL"
"TPIPP"
"TPL"
"TPLAS"
"TPOLY"
"TPP"
"TPRIME"
"TPS"
"TQM"
"TQR"
"TR"
"TRC"
"TRITN"
"TRP"
"TRT"
"TRU"
"TRUBB"
"TRUE"
"TRV"
"TSC"
"TSE"
"TSI"
"TSR"
"TSTE"
"TSTH"
"TTA"
"TTB"
"TTCL"
"TTI"
"TTLPF"
"TTT"
"TTW"
"TU"
"TU-PF"
"TURBO"
"TURTLE"
"TVDH"
"TVH"
"TVO"
"TVT"
"TWP"
"TWPC"
"TWZ"
"TYCN"
"UAC"
"UBA"
"UBE"
"UBIS"
"UEC"
"UKEM"
"UMI"
"UMS"
"UNIQ"
"UOBKH"
"UP"
"UPF"
"UPOIC"
"UREKA"
"UTP"
"UV"
"UVAN"
"VARO"
"VCOM"
"VGI"
"VIBHA"
"VIH"
"VL"
"VNG"
"VPO"
"VRANDA"
"VS"
"WACOAL"
"WARRIX"
"WASH"
"WAVE"
"WELL"
"WFX"
"WGE"
"WHA"
"WHABT"
"WHAIR"
"WHART"
"WHAUP"
"WICE"
"WIIK"
"WIN"
"WINDOW"
"WINMED"
"WINNER"
"WORK"
"WP"
"WPH"
"WSOL"
"XBIO"
"XO"
"XPG"
"XYZ"
"YGG"
"YONG"
"YUASA"
"ZAA"
"ZEN"
"ZIGA"


"""

## เติม. BK

In [28]:
symbols = [s.strip() for s in raw.split("\n") if s.strip()]

# ลบ .BK ซ้ำ + เติมใหม่
symbols = [s.replace(".BK", "") + ".BK" for s in symbols]

# ลบซ้ำ
symbols = list(set(symbols))

print("Total symbols:", len(symbols))
print(symbols[:10])

Total symbols: 932
['"APO".BK', '"ASIAN".BK', '"KUN".BK', '"BKA".BK', '"PERM".BK', '"SRICHA".BK', '"SCB".BK', '"PF".BK', '"GULF".BK', '"KCE".BK']

In [29]:
#(Clean Symbol ให้ถูกต้อง)
symbols = [s.strip().replace('"', '').replace(".BK", "") + ".BK" for s in symbols]

In [30]:
symbols = list(set(symbols))  # ลบซ้ำ
symbols = [s.strip().replace('"','').replace(".BK","") + ".BK" for s in symbols]

In [31]:
print(symbols[:20])

['IROYAL.BK', 'SCGD.BK', 'BUI.BK', 'SVT.BK', 'TURTLE.BK', 'BR.BK', 'APCS.BK', 'SPACK.BK', 'PEACE.BK', 'SKN.BK', 'VL.BK', 'KIAT.BK', 'TNR.BK', 'UTP.BK', 'MGI.BK', 'DOD.BK', 'S.BK', 'ABM.BK', 'AI.BK', 'ANI.BK']

## ดึง market cap

In [38]:
import yfinance as yf
import pandas as pd
import time
from tqdm import tqdm

def fetch_market_cap_batch(batch):
    results = []
    
    tickers = yf.Tickers(" ".join(batch))

    for sym in batch:
        try:
            ticker = tickers.tickers.get(sym)
            info = ticker.info if ticker else {}

            results.append({
                "symbol": sym.replace(".BK", ""),
                "market_cap": info.get("marketCap", None)
            })

        except:
            results.append({
                "symbol": sym.replace(".BK", ""),
                "market_cap": None
            })

    return results

In [39]:
BATCH_SIZE = 50
all_data = []

for i in tqdm(range(0, len(symbols), BATCH_SIZE)):
    batch = symbols[i:i+BATCH_SIZE]
    
    result = fetch_market_cap_batch(batch)
    all_data.extend(result)

    time.sleep(1)

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WELL.BK"}}}
100%|███████████████████████████████████████████| 19/19 [03:26<00:00, 10.86s/it]

In [40]:
from datetime import datetime

df_mc = pd.DataFrame(all_data)
df_mc["updated_at"] = datetime.today().date()

df_mc.head()

   symbol    market_cap  updated_at
0  IROYAL  1.230500e+09  2026-04-07
1    SCGD  8.019000e+09  2026-04-07
2     BUI  6.182095e+08  2026-04-07
3     SVT  8.750000e+08  2026-04-07
4  TURTLE  4.101037e+09  2026-04-07

## แปลง market_cap

In [43]:
df_mc["market_cap"] = df_mc["market_cap"].astype("int64")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

มีค่า NaN (None) อยู่ใน column market_cap
→ เลยแปลงเป็น int ไม่ได้

In [44]:
pd.options.display.float_format = '{:,.0f}'.format

df_mc.head()

   symbol    market_cap  updated_at
0  IROYAL 1,230,499,968  2026-04-07
1    SCGD 8,019,000,320  2026-04-07
2     BUI   618,209,536  2026-04-07
3     SVT   875,000,000  2026-04-07
4  TURTLE 4,101,037,056  2026-04-07

In [45]:
df_valid = df_mc[df_mc["market_cap"].notna()]
df_invalid = df_mc[df_mc["market_cap"].isna()]

## ใช้ df_valid เป็นตัวหลัก

In [47]:
df_valid.head()

   symbol    market_cap  updated_at
0  IROYAL 1,230,499,968  2026-04-07
1    SCGD 8,019,000,320  2026-04-07
2     BUI   618,209,536  2026-04-07
3     SVT   875,000,000  2026-04-07
4  TURTLE 4,101,037,056  2026-04-07

## ทำความสะอาด + แปลง type

In [48]:
df_valid["market_cap"] = df_valid["market_cap"].astype("int64")

/var/folders/31/9k1nqy5s707g8pz9zy6gwnyr0000gn/T/ipykernel_49678/2576565590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid["market_cap"] = df_valid["market_cap"].astype("int64")

## เรียงลำดับ

In [49]:
df_valid = df_valid.sort_values(by="market_cap", ascending=False)

## สร้าง Ranking

In [50]:
df_valid["rank"] = df_valid["market_cap"].rank(ascending=False)

## เเบ่งขนาดหุ้น

In [51]:
df_valid["size"] = pd.qcut(
    df_valid["market_cap"],
    3,
    labels=["Small Cap", "Mid Cap", "Large Cap"]
)

In [52]:
df_valid.head(10)

     symbol     market_cap  updated_at  rank       size
414   DELTA  3367930429440  2026-04-07     1  Large Cap
20   ADVANC  1085586604032  2026-04-07     2  Large Cap
294     PTT   970108502016  2026-04-07     3  Large Cap
226    GULF   885185380352  2026-04-07     4  Large Cap
587     AOT   757142126592  2026-04-07     5  Large Cap
572   PTTEP   623287664640  2026-04-07     6  Large Cap
410    TRUE   501005418496  2026-04-07     7  Large Cap
544     KTB   492656132096  2026-04-07     8  Large Cap
241     SCB   486546997248  2026-04-07     9  Large Cap
70    KBANK   451356917760  2026-04-07    10  Large Cap

## บันทึกลง PostgreSQL

In [56]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
import time

In [57]:
engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")
print ('เชื่อมต่อ')

เชื่อมต่อ

In [58]:
df_valid.to_sql(
    "market_cap",
    engine,
    if_exists="append",
    index=False
)

918

In [59]:
df_invalid.head()

      symbol  market_cap  updated_at
34    KBSPIF         NaN  2026-04-07
109      BKA         NaN  2026-04-07
122  CPTREIT         NaN  2026-04-07
164   BTSGIF         NaN  2026-04-07
199      DIF         NaN  2026-04-07

In [60]:
df_invalid.to_sql(
    "missing_market_cap",
    engine,
    if_exists="append",
    index=False
)

14

In [61]:
print("Total:", len(df_mc))
print("Valid:", len(df_valid))
print("Missing:", len(df_invalid))

Total: 932
Valid: 918
Missing: 14

In [63]:
df_valid.to_sql(
    "temp_market_cap",
    engine,
    if_exists="replace",
    index=False
)

918

In [64]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        UPDATE prices p
        SET market_cap = t.market_cap
        FROM temp_market_cap t
        JOIN stocks s ON s.symbol = t.symbol
        WHERE p.stock_id = s.stock_id;
    """))

In [65]:
import pandas as pd

check = pd.read_sql("""
    SELECT p.stock_id, s.symbol, p.market_cap
    FROM prices p
    JOIN stocks s ON p.stock_id = s.stock_id
    WHERE p.market_cap IS NOT NULL
    LIMIT 10;
""", engine)

check

   stock_id   symbol    market_cap
0       828   MASTEC   354,000,000
1      1011      NUT   503,999,968
2      1099      QDC    27,954,804
3      1184  SIRIPRT 1,164,499,968
4      1184  SIRIPRT 1,164,499,968
5       828   MASTEC   354,000,000
6       828   MASTEC   354,000,000
7       828   MASTEC   354,000,000
8       828   MASTEC   354,000,000
9       828   MASTEC   354,000,000

In [66]:
df_valid.drop_duplicates(subset=["symbol"])

     symbol     market_cap  updated_at  rank       size
414   DELTA  3367930429440  2026-04-07     1  Large Cap
20   ADVANC  1085586604032  2026-04-07     2  Large Cap
294     PTT   970108502016  2026-04-07     3  Large Cap
226    GULF   885185380352  2026-04-07     4  Large Cap
587     AOT   757142126592  2026-04-07     5  Large Cap
..      ...            ...         ...   ...        ...
762     KKC       60000000  2026-04-07   914  Small Cap
911     CHO       45974084  2026-04-07   915  Small Cap
42      MVP       40471116  2026-04-07   916  Small Cap
123     QDC       27954804  2026-04-07   917  Small Cap
470      CV       25647054  2026-04-07   918  Small Cap

[918 rows x 5 columns]

ดึง market cap จาก yfinance (900 ตัว)
✔ แก้ error (.BK / symbol / 404)
✔ clean data
✔ แยก valid / invalid
✔ update ลง PostgreSQL สำเร็จ
✔ เชื่อมกับ stock_id ได้ถูกต้อง