In [44]:
!pip install yfinance pandas sqlalchemy psycopg2-binary

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [45]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
import time

In [46]:
engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")
print ('เชื่อมต่อ')

เชื่อมต่อ

In [47]:
import pandas as pd

tickers = [
"NSL","NTF","NTSC","NTV","NUT","NV","NVD","NWR","NYT","OCC",
"OGC","OHTL","OKJ","ONEE","ONSENS","OR","ORI","ORN","OSP","PACO",
"PAF","PANEL","PAP","PATO","PB","PCC","PCE","PCSGH","PDG","PDJ",
"PEACE","PEER","PERM","PF","PG","PHG","PHOL","PICO","PIMO","PIN",
"PIS","PJW","PK","PL","PLANB","PLANET","PLAT","PLE","PLT","PLUS",
"PM","PMC","PMTA","POLY","POPF","PORT","PPM","PPP","PPPM","PPS",
"PQS","PR9","PRAKIT","PRAPAT","PREB","PRECHA","PRG","PRI","PRIME","PRIN",
"PRINC","PRM","PROEN","PROS","PROSPECT","PROUD","PRTR","PSGC","PSH","PSL",
"PSP","PSTC","PT","PTC","PTECH","PTG","PTL","PTT","PTTEP","PTTGC",
"PYLON","Q-CON","QDC","QH","QHBREIT","QHHRREIT","QHOP","QLT","QTC","QTCG",
"RABBIT","RAM","RATCH","RBF","RCL","READY","RICHY","RJH","RML","ROCK",
"ROCTEC","ROH","ROJNA","RP","RPC","RPH","RS","RSP","RT","RWI",
"S","S&J","S11","SA","SAAM","SABINA","SAF","SAFE","SAK","SALEE",
"SAM","SAMART","SAMCO","SAMTEL","SANKO","SAPPE","SAT","SAUCE","SAV","SAWAD",
"SAWANG","SC","SCAP","SCB","SCC","SCCC","SCG","SCGD","SCGP","SCI",
"SCL","SCM","SCN","SCP","SDC","SE","SEAFCO","SEAOIL","SECURE","SE-ED",
"SEI","SELIC","SENA","SENX","SFLEX","SFT","SGC","SGF","SGP","SHANG",
"SHR","SIAM","SICT","SIMAT","SINGER","SINO","SIRI","SIRIPRT","SIS","SISB",
"SITHAI","SJWD","SK","SKE","SKIN","SKN","SKR","SKY","SLP","SMART",
"SMD100","SMIT","SMO","SMPC","SMT","SNC","SNNP","SNP","SNPS"
]

df_stocks = pd.DataFrame({"symbol": tickers})

df_stocks.head()

  symbol
0    NSL
1    NTF
2   NTSC
3    NTV
4    NUT

In [48]:
df_stocks.to_sql("stocks", engine, if_exists="append", index=False)

199

In [49]:
#เช็คว่าเข้าแล้ว
pd.read_sql("SELECT * FROM stocks LIMIT 10", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20,None,None,None,None
1,2,3BBIF,3BB Internet Infrastructure Fund,20,None,None,None,None
2,3,88TH,88(Thailand) Public Company Limited,20,None,None,None,None
3,4,A,Areeya Property Public Company Limited,20,None,None,None,None
4,5,A5,Asset Five Group Public Company Limited,20,None,None,None,None
5,6,AAI,Asian Alliance International Public Company Li...,20,None,None,None,None
6,7,AAV,Asia Aviation Public Company Limited,11,None,None,None,None
7,8,ABM,Asia Biomass Public Company Limited,20,None,None,None,None
8,9,ACAP,Asia Capital Group Public Company Limited,20,None,None,None,None
9,10,ACC,Advanced Connection Corporation Public Company...,20,None,None,None,None

In [50]:
# เติม .BK
tickers_yf = [t + ".BK" for t in tickers]

data = yf.download(
    tickers_yf,
    period="1y",
    group_by="ticker",
    progress=False
)

In [51]:
#ดูชื่อหุ้นที่โหลดได้
data.columns.levels[0]

Index(['NSL.BK', 'NTF.BK', 'NTSC.BK', 'NTV.BK', 'NUT.BK', 'NV.BK', 'NVD.BK',
       'NWR.BK', 'NYT.BK', 'OCC.BK',
       ...
       'SMART.BK', 'SMD100.BK', 'SMIT.BK', 'SMO.BK', 'SMPC.BK', 'SMT.BK',
       'SNC.BK', 'SNNP.BK', 'SNP.BK', 'SNPS.BK'],
      dtype='object', name='Ticker', length=199)

In [53]:
#เฉพาะหุ้นตัวเดียว
data["NSL.BK"].head()

Price            Open       High        Low      Close   Volume
Date
2025-04-03  27.543325  28.026542  27.301717  27.543325   761400
2025-04-04  27.543325  28.026541  27.301717  27.784933   790200
2025-04-08  27.543326  27.543326  25.610461  26.335285  1711100
2025-04-09  26.093676  26.576892  25.610459  26.093676   800600
2025-04-10  26.818501  27.784934  26.576893  27.543325  1200900

In [54]:
data.head()

Ticker        PCE.BK                                        SKE.BK        \
Price           Open      High       Low     Close   Volume   Open  High
Date
2025-04-03  2.807945  2.826918  2.732055  2.788973  6672000   0.19  0.20
2025-04-04  2.788973  2.807945  2.732055  2.770000  3413400   0.20  0.20
2025-04-08  2.694110  2.770000  2.637192  2.656164  5212100   0.19  0.20
2025-04-09  2.656164  2.732055  2.523356  2.713082  9031500   0.17  0.18
2025-04-10  2.770000  2.788973  2.656164  2.751028  9021100   0.18  0.18

Ticker                           ... PF.BK                             \
Price        Low Close   Volume  ...  Open  High   Low Close   Volume
Date                             ...
2025-04-03  0.19  0.20   152100  ...  0.11  0.11  0.10  0.10  2222800
2025-04-04  0.18  0.20   380300  ...  0.10  0.11  0.09  0.09  9637400
2025-04-08  0.17  0.18  1249200  ...  0.09  0.10  0.09  0.09  7638300
2025-04-09  0.16  0.18   650400  ...  0.09  0.10  0.09  0.09  1367700
2025-04-10  0.17  0.18   167200  ...  0.10  0.10  0.09  0.09  5402400

Ticker         NTV.BK
Price            Open       High        Low      Close Volume
Date
2025-04-03  26.511374  26.511374  26.033691  26.033691  19900
2025-04-04  26.033691  26.033691  25.078326  25.794849  58000
2025-04-08  25.317167  25.794850  24.122961  25.317167  45900
2025-04-09  26.272532  26.272532  23.884120  25.794849  52300
2025-04-10  25.556009  25.794851  25.317168  25.556009  11500

[5 rows x 995 columns]

In [55]:
#แปลงข้อมูลให้พร้อมใช้
all_data = []

for t in tickers_yf:
    try:
        df = data[t].copy()
        df["symbol"] = t.replace(".BK", "")
        df = df.reset_index()
        all_data.append(df)
    except:
        print(f"❌ ไม่มีข้อมูล: {t}")

final_df = pd.concat(all_data)
final_df.columns = [c.lower().replace(" ", "_") for c in final_df.columns]

final_df.head()

        date       open       high        low      close     volume symbol
0 2025-04-03  27.543325  28.026542  27.301717  27.543325   761400.0    NSL
1 2025-04-04  27.543325  28.026541  27.301717  27.784933   790200.0    NSL
2 2025-04-08  27.543326  27.543326  25.610461  26.335285  1711100.0    NSL
3 2025-04-09  26.093676  26.576892  25.610459  26.093676   800600.0    NSL
4 2025-04-10  26.818501  27.784934  26.576893  27.543325  1200900.0    NSL

In [56]:
#map เป็น stock_id
stocks_df = pd.read_sql("SELECT stock_id, symbol FROM stocks", engine)

stock_map = dict(zip(stocks_df["symbol"], stocks_df["stock_id"]))

final_df["stock_id"] = final_df["symbol"].map(stock_map)

In [57]:
#ปรับ column ให้ตรง DB
final_df.rename(columns={
    "date": "trade_date"
}, inplace=True)

final_df = final_df[
    ["trade_date", "open", "high", "low", "close", "volume", "stock_id"]
]

In [58]:
final_df.head()

  trade_date       open       high        low      close     volume  stock_id
0 2025-04-03  27.543325  28.026542  27.301717  27.543325   761400.0      1007
1 2025-04-04  27.543325  28.026541  27.301717  27.784933   790200.0      1007
2 2025-04-08  27.543326  27.543326  25.610461  26.335285  1711100.0      1007
3 2025-04-09  26.093676  26.576892  25.610459  26.093676   800600.0      1007
4 2025-04-10  26.818501  27.784934  26.576893  27.543325  1200900.0      1007

In [59]:
final_df.isnull().sum()

trade_date       0
open          1097
high          1097
low           1097
close         1097
volume        1097
stock_id         0
dtype: int64

In [60]:
len(final_df)

48158

In [61]:
final_df.to_sql(
    "prices",
    engine,
    if_exists="append",
    index=False
)

158

In [62]:
pd.read_sql("SELECT * FROM prices ORDER BY trade_date DESC LIMIT 10", engine)

,price_id,stock_id,trade_date,open,high,low,close,volume,market_cap
0,104468,819,2026-04-03,4.700000,4.78,4.620000,4.720000,109800,None
1,105678,824,2026-04-03,19.799999,19.90,19.600000,19.600000,286558,None
2,102532,811,2026-04-03,4.300000,4.34,4.300000,4.340000,139900,None
3,103500,815,2026-04-03,3.680000,3.68,3.660000,3.680000,27100,None
4,104952,821,2026-04-03,8.850000,8.90,8.700000,8.900000,30000,None
5,105194,822,2026-04-03,19.500000,19.50,18.799999,18.799999,2938800,None
6,101564,807,2026-04-03,3.800000,3.80,3.740000,3.740000,14005200,None
7,102048,809,2026-04-03,13.000000,13.10,12.900000,12.900000,697300,None
8,102774,812,2026-04-03,14.100000,14.20,14.000000,14.000000,148100,None
9,105920,825,2026-04-03,7.500000,7.65,7.400000,7.600000,1728400,None

In [63]:
symbols  = ["NSL","NTF","NTSC","NTV","NUT","NV","NVD","NWR","NYT","OCC",
"OGC","OHTL","OKJ","ONEE","ONSENS","OR","ORI","ORN","OSP","PACO",
"PAF","PANEL","PAP","PATO","PB","PCC","PCE","PCSGH","PDG","PDJ",
"PEACE","PEER","PERM","PF","PG","PHG","PHOL","PICO","PIMO","PIN",
"PIS","PJW","PK","PL","PLANB","PLANET","PLAT","PLE","PLT","PLUS",
"PM","PMC","PMTA","POLY","POPF","PORT","PPM","PPP","PPPM","PPS",
"PQS","PR9","PRAKIT","PRAPAT","PREB","PRECHA","PRG","PRI","PRIME","PRIN",
"PRINC","PRM","PROEN","PROS","PROSPECT","PROUD","PRTR","PSGC","PSH","PSL",
"PSP","PSTC","PT","PTC","PTECH","PTG","PTL","PTT","PTTEP","PTTGC",
"PYLON","Q-CON","QDC","QH","QHBREIT","QHHRREIT","QHOP","QLT","QTC","QTCG",
"RABBIT","RAM","RATCH","RBF","RCL","READY","RICHY","RJH","RML","ROCK",
"ROCTEC","ROH","ROJNA","RP","RPC","RPH","RS","RSP","RT","RWI",
"S","S&J","S11","SA","SAAM","SABINA","SAF","SAFE","SAK","SALEE",
"SAM","SAMART","SAMCO","SAMTEL","SANKO","SAPPE","SAT","SAUCE","SAV","SAWAD",
"SAWANG","SC","SCAP","SCB","SCC","SCCC","SCG","SCGD","SCGP","SCI",
"SCL","SCM","SCN","SCP","SDC","SE","SEAFCO","SEAOIL","SECURE","SE-ED",
"SEI","SELIC","SENA","SENX","SFLEX","SFT","SGC","SGF","SGP","SHANG",
"SHR","SIAM","SICT","SIMAT","SINGER","SINO","SIRI","SIRIPRT","SIS","SISB",
"SITHAI","SJWD","SK","SKE","SKIN","SKN","SKR","SKY","SLP","SMART",
"SMD100","SMIT","SMO","SMPC","SMT","SNC","SNNP","SNP","SNPS"
]

In [64]:
!pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [65]:
import yfinance as yf
import pandas as pd

data = []

for sym in symbols:
    try:
        ticker = yf.Ticker(sym + ".BK")  # หุ้นไทยต้องเติม .BK
        info = ticker.info
        name = info.get("longName") or info.get("shortName") or sym
        
        data.append({
            "symbol": sym,
            "stock_name": name
        })
    except:
        data.append({
            "symbol": sym,
            "stock_name": sym
        })

df = pd.DataFrame(data)
df

    symbol                                         stock_name
0      NSL                   NSL Foods Public Company Limited
1      NTF   NTF Intergroup (Thailand) Public Company Limited
2     NTSC                Nutrition SC Public Company Limited
3      NTV          Nonthavej Hospital Public Company Limited
4      NUT           Nutrition Profess Public Company Limited
..     ...                                                ...
194    SMT  Stars Microelectronics (Thailand) Public Compa...
195    SNC                  SNC Former Public Company Limited
196   SNNP       Srinanaporn Marketing Public Company Limited
197    SNP               S&P Syndicate Public Company Limited
198   SNPS                    SNPS_SPECIALTY NATURAL PRODUCTS

[199 rows x 2 columns]

In [66]:
df.head()

  symbol                                        stock_name
0    NSL                  NSL Foods Public Company Limited
1    NTF  NTF Intergroup (Thailand) Public Company Limited
2   NTSC               Nutrition SC Public Company Limited
3    NTV         Nonthavej Hospital Public Company Limited
4    NUT          Nutrition Profess Public Company Limited

In [67]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/thai_stock_market"
)

In [68]:
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in df.iterrows():
        conn.execute(text("""
            INSERT INTO stocks (symbol, stock_name)
            VALUES (:symbol, :stock_name)
            ON CONFLICT (symbol)
            DO UPDATE SET
                stock_name = EXCLUDED.stock_name
        """), {
            "symbol": row["symbol"],
            "stock_name": row["stock_name"]
        })

print("✅ Upsert completed (no duplicate error)")

✅ Upsert completed (no duplicate error)

In [69]:
pd.read_sql("SELECT * FROM stocks ORDER BY symbol", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20.0,None,None,None,None
1,2,3BBIF,3BB Internet Infrastructure Fund,20.0,None,None,None,None
2,3,88TH,88(Thailand) Public Company Limited,20.0,None,None,None,None
3,4,A,Areeya Property Public Company Limited,20.0,None,None,None,None
4,5,A5,Asset Five Group Public Company Limited,20.0,None,None,None,None
...,...,...,...,...,...,...,...,...
692,1201,SMT,Stars Microelectronics (Thailand) Public Compa...,NaN,None,None,None,None
693,1202,SNC,SNC Former Public Company Limited,NaN,None,None,None,None
694,1203,SNNP,Srinanaporn Marketing Public Company Limited,NaN,None,None,None,None
695,1204,SNP,S&P Syndicate Public Company Limited,NaN,None,None,None,None
696,1205,SNPS,SNPS_SPECIALTY NATURAL PRODUCTS,NaN,None,None,None,None

In [2]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
import time

In [3]:
engine = create_engine("postgresql://postgres:1234@localhost:5432/thai_stock_market")
print ('เชื่อมต่อ')

เชื่อมต่อ

In [5]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:your_password@localhost:5432/thai_stock_market")

df = pd.read_sql("SELECT * FROM stocks", engine)

df.head()

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20.0,10.54,0.74,0.26,8.63
1,2,3BBIF,3BB Internet Infrastructure Fund,20.0,NaN,NaN,NaN,NaN
2,3,88TH,88(Thailand) Public Company Limited,20.0,8.64,2.11,0.56,3.73
3,4,A,Areeya Property Public Company Limited,20.0,NaN,3.19,-0.99,NaN
4,5,A5,Asset Five Group Public Company Limited,20.0,20.56,1.30,0.09,2.72

In [6]:
# เช็ค NULL
df["category_id"].isnull().sum()

np.int64(734)

In [7]:
# ดูการกระจาย
df["category_id"].value_counts().sort_index()

category_id
2.0       3
3.0       8
4.0       3
5.0       6
6.0       8
7.0       4
8.0       6
9.0       3
11.0      9
12.0      1
13.0      3
20.0    144
Name: count, dtype: int64

In [8]:
df[df["symbol"].isin(["PTT","SCB","AOT","CPALL","DELTA"])]

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
61,51,AOT,Airports of Thailand Public Company Limited,11.0,43.09,5.59,1.23,1.51
246,183,CPALL,CP ALL Public Company Limited,7.0,14.68,3.16,3.10,3.63
263,414,DELTA,Delta Electronics (Thailand) Public Company Li...,NaN,136.36,34.82,1.98,0.22
586,1094,PTT,PTT Public Company Limited,NaN,10.87,0.86,3.15,5.92
663,1150,SCB,SCB X Public Company Limited,NaN,10.25,0.98,14.10,7.75

In [9]:
symbols = """
CRD CREDIT CSC CSP CSR CSS CTARAF CTW CV CWT
D DCC DCON DDD DELTA DEMCO DEXON DHOUSE DIF DIMET
DITTO DMT DOD DOHOME DPAINT DREIT DRT DTCENT DTCI DUSIT
DV8 EA EASON EAST EASTW ECF EFORL EGATIF EGCO EKH
EMC EMPIRE EP EPG ERW ESTAR ETC ETE ETL EURO
EVER F&D FANCY FE FLOYD FM FMT FN FNS FORTH
FPI FPT FSMART FSX FTE FTI FTREIT FUTURERT FVC GABLE
GAHREIT GBX GC GCAP GEL GENCO GFC GFPT GGC GJS
GLAND GLOBAL GLORY GPI GPSC GRAMMY GRAND GREEN GROREIT GSTEEL
GTB GTV GULF GUNKUL GVREIT GYT HANA HANN HARN HEALTH
HENG HFT HL HMPRO HPF HPT HTC HTECH HUMAN HYDRO
HYDROGEN I2 ICC ICHI ICN IDG IFS IHL IIG III
ILINK ILM IMH IMPACT IND INET INETREIT INGRS INOX INSET
INSURE IP IRC IRCP IROYAL IRPC ISSARA IT ITC ITD
ITEL ITNS ITTHI IVF IVL J JAK JAS JCK JCT
JMART JMT JPARK JR JSP JTS JUBILE K KAMART KASET
KBANK KBS KBSPIF KC KCAR KCC KCE KCG KCM KDH
KGEN KGI KIAT KISS KJL KK KKC KKP KLINIQ KOOL
KPNREIT KSL KTB KTBSTMR KTC KTIS KTMS KUMWEL KUN KWC
KWI KWM KYE L&E LALIN LANNA LDC LEE LEO LH
LHFG LHHOTEL LHK LHRREIT LHSC LIT LOXLEY LPH LPN LRH
LST LTMH LTS LUXF M MADAME MAGURO MAJOR MALEE MANRIN
MASTEC MASTER MATCH MATI MBAX MBK MC MCA M-CHAI MCOT
MCS MDX MEB MEDEZE MEGA MENA META METCO MFC MFEC
MGC MGI MGT MICRO MIDA MII MILL MINT MIPF MITSIB
MJD MJLF MK ML MMM MNIT MNIT2 MNRF MODERN MONO
MOONG MORE MOSHI MOTHER M-PAT MPJ MRDIYT MSC MST
M-STOR MTC MTI MTW MUD MVP NAM NAT NATION NC
NCAP NCH NCL NCP NDR NEO NEP NER NETBAY NEW
NEX NFC NKI NKT NL NNCL NOBLE NOVA NPK NRF
NSL NTF NTSC NTV NUT NV NVD NWR NYT OCC
OGC OHTL OKJ ONEE ONSENS OR ORI ORN OSP
PACO PAF PANEL PAP PATO PB PCC PCE PCSGH PDG
PDJ PEACE PEER PERM PF PG PHG PHOL PICO PIMO
PIN PIS PJW PK PL PLANB PLANET PLAT PLE PLT
PLUS PM PMC PMTA POLY POPF PORT PPM PPP PPPM
PPS PQS PR9 PRAKIT PRAPAT PREB PRECHA PRG PRI
PRIME PRIN PRINC PRM PROEN PROS PROSPECT PROUD PRTR PSGC
PSH PSL PSP PSTC PT PTC PTECH PTG PTL PTT
PTTEP PTTGC PYLON Q-CON QDC QH QHBREIT QHHRREIT QHOP QLT
QTC QTCG RABBIT RAM RATCH RBF RCL READY RICHY RJH
RML ROCK ROCTEC ROH ROJNA RP RPC RPH RS
RSP RT RWI S S&J S11 SA SAAM SABINA SAF
SAFE SAK SALEE SAM SAMART SAMCO SAMTEL SANKO SAPPE
SAT SAUCE SAV SAWAD SAWANG SC SCAP SCB SCC
SCCC SCG SCGD SCGP SCI SCL SCM SCN SCP
SDC SE SEAFCO SEAOIL SECURE SE-ED SEI SELIC SENA SENX
SFLEX SFT SGC SGF SGP SHANG SHR SIAM SICT SIMAT
SINGER SINO SIRI SIRIPRT SIS SISB SITHAI SJWD SK
SKE SKIN SKN SKR SKY SLP SMART SMD100 SMIT
SMO SMPC SMT SNC SNNP SNP SNPS SO SOLAR
SONIC SORKON SPA SPACK SPALI SPC SPCG SPG SPI
SPRC SPREME SPRIME SPTX SPVI SQ SR SRICHA SRIPANWA
SRS SSF SSP SSPF SSSC SST SSTRT STA STANLY STARM
STC STECH STECON STELLA STGT STI STOWER STP STPI
STX SUC SUN SUPER SUPEREIF SUSCO SUTHA SVI SVOA
SVR SVT SWC SYMC SYNEX SYNTEC TACC TAE TAKUNI TAN
TAPAC TASCO TATG TBN TC TCAP TCC TCJ TCMC
TCOAT TEAM TEAMG TEGH TEKA TERA TFFIF TFG TFI
TFM TFMAMA TGE TGH TGPRO TH THAI THANA THANI THCOM
THE THG THIP THMUI THRE THREL TIDLOR TIF1 TIGER TIPCO
TIPH TISCO TITLE TK TKC TKN TKS TKT TL TLHPF
TLI TM TMAN TMC TMD TMI TMILL TMT TMW TNDT
TNH TNITY TNL TNP TNPC TNPF TNR TOA TOG TOP
TOPP TPA TPAC TPBI TPCH TPCS TPIPL TPIPP TPL TPLAS
TPOLY TPP TPRIME TPS TQM TQR TR TRC TRITN TRP
TRT TRU TRUBB TRUE TRV TSC TSE TSI TSR TSTE
TSTH TTA TTB TTCL TTI TTLPF TTT TTW TU TU-PF
TURBO TURTLE TVDH TVH TVO TVT TWP TWPC TWZ TYCN
UAC UBA UBE UBIS UEC UKEM UMI UMS UNIQ UOBKH
UP UPF UPOIC UREKA UTP UV UVAN VARO VCOM VGI
VIBHA VIH VL VNG VPO VRANDA VS WACOAL WARRIX WASH
WAVE WELL WFX WGE WHA WHABT WHAIR WHART WHAUP WICE
WIIK WIN WINDOW WINMED WINNER WORK WP WPH WSOL
XBIO XO XPG XYZ YGG YONG YUASA ZAA ZEN ZIGA
"""

symbols = symbols.split()

In [10]:
def map_category(sym):
    s = sym.upper()

    # REIT & PF
    if "REIT" in s or "PF" in s or "IFF" in s:
        return 19

    # Banking
    if s in ["KBANK","SCB","KTB","TTB","BBL","KKP","TISCO"]:
        return 4

    # Finance
    if s in ["MTC","SAWAD","KTC","AEONTS","JMT","BAM"]:
        return 5

    # Energy
    if s.startswith(("PTT","PTTEP","PTTGC","GULF","GPSC","EA","EGCO","RATCH","SPRC","TOP")):
        return 3

    # ICT
    if s.startswith(("ADVANC","TRUE","DTAC","INTUCH","INET","IT","JAS","THCOM","ILINK")):
        return 6

    # Commerce
    if s.startswith(("CPALL","HMPRO","GLOBAL","DOHOME","CRC","COM7","BJC","MAKRO")):
        return 7

    # Property
    if s.startswith(("LH","ORI","SPALI","SIRI","QH","NOBLE","SC","LPN","ANAN")):
        return 8

    # Construction Services
    if s.startswith(("ITD","STEC","UNIQ","SEAFCO","PYLON","CK")):
        return 9

    # Construction Materials
    if s.startswith(("SCC","TPIPL","TOA","TASCO")):
        return 10

    # Transport
    if s.startswith(("AOT","BEM","BTS","RCL","PSL","WICE","SJWD","PORT")):
        return 11

    # Tourism
    if s.startswith(("MINT","CENTEL","ERW","DUSIT","SPA")):
        return 12

    # Health
    if s.startswith(("BDMS","BH","CHG","RAM","VIH","EKH")):
        return 13

    # Media
    if s.startswith(("WORK","MONO","GRAMMY","RS","ONEE")):
        return 14

    # Packaging
    if s.startswith(("SCGP","BGC")):
        return 15

    # Industrial
    if s.startswith(("DELTA","HANA","KCE","SVI","SMT")):
        return 16

    # Automotive
    if s.startswith(("SAT","AH","STANLY")):
        return 17

    # Insurance
    if s.startswith(("TIPH","THRE","TVH","BLA")):
        return 18

    # Food
    if s.startswith(("CPF","TU","GFPT","OSP","ICHI","SAPPE","TKN")):
        return 2

    # Agro
    if s.startswith(("STA","NER","TRUBB")):
        return 1

    # Default
    return 20

In [13]:
import pandas as pd

df = pd.DataFrame(symbols, columns=["symbol"])
df["category_id"] = df["symbol"].apply(map_category)

df.head()

   symbol  category_id
0     CRD           20
1  CREDIT           20
2     CSC           20
3     CSP           20
4     CSR           20

In [14]:
df["category_id"].value_counts().sort_index()

category_id
1       4
2       8
3      14
4       6
5       4
6      11
7       3
8      25
9       5
10      3
11      5
12      5
13      3
14      6
16      5
17      2
18      4
19     20
20    600
Name: count, dtype: int64

In [15]:
from psycopg2.extras import execute_batch
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="thai_stock_market",
    user="postgres",
    password="admin"
)
cur = conn.cursor()

data = list(df.itertuples(index=False, name=None))

execute_batch(cur, """
UPDATE stocks
SET category_id = %s
WHERE symbol = %s
""", [(cat, sym) for sym, cat in data])

conn.commit()
cur.close()
conn.close()